import type { Player } from "@/types/simulation";

// Generated from first-game regular-season box scores in NocturneBear/NBA-Data-2010-2024.
// If an opening box score had fewer than eight active players, remaining slots use that team season's minutes leaders.
export type RosterPlayerInput = [string, Player["position"]];

export const modernRosterPlayers: Record<string, RosterPlayerInput[]> = {
  "2014-15|Atlanta Hawks": [
    ["Kyle Korver", "G"],
    ["Jeff Teague", "G"],
    ["Paul Millsap", "F"],
    ["DeMarre Carroll", "F"],
    ["Al Horford", "C"],
    ["Mike Scott", "F"],
    ["Thabo Sefolosha", "F"],
    ["Shelvin Mack", "G"],
  ],
  "2014-15|Boston Celtics": [
    ["Jeff Green", "F"],
    ["Avery Bradley", "G"],
    ["Rajon Rondo", "G"],
    ["Kelly Olynyk", "C"],
    ["Jared Sullinger", "F"],
    ["Marcus Smart", "G"],
    ["Evan Turner", "F"],
    ["Brandon Bass", "F"],
  ],
  "2014-15|Brooklyn Nets": [
    ["Deron Williams", "G"],
    ["Joe Johnson", "F"],
    ["Jarrett Jack", "G"],
    ["Bojan Bogdanovic", "G"],
    ["Alan Anderson", "G"],
    ["Mirza Teletovic", "F"],
    ["Kevin Garnett", "F"],
    ["Mason Plumlee", "C"],
  ],
  "2014-15|Charlotte Hornets": [
    ["Al Jefferson", "C"],
    ["Lance Stephenson", "G"],
    ["Kemba Walker", "G"],
    ["Michael Kidd-Gilchrist", "F"],
    ["Marvin Williams", "F"],
    ["Gary Neal", "G"],
    ["Cody Zeller", "F"],
    ["Brian Roberts", "G"],
  ],
  "2014-15|Chicago Bulls": [
    ["Mike Dunleavy", "F"],
    ["Pau Gasol", "F"],
    ["Taj Gibson", "F"],
    ["Doug McDermott", "F"],
    ["Kirk Hinrich", "G"],
    ["Aaron Brooks", "G"],
    ["Derrick Rose", "G"],
    ["Joakim Noah", "C"],
  ],
  "2014-15|Cleveland Cavaliers": [
    ["LeBron James", "F"],
    ["Kyrie Irving", "G"],
    ["Kevin Love", "F"],
    ["Dion Waiters", "G"],
    ["Anderson Varejao", "C"],
    ["Tristan Thompson", "C"],
    ["Matthew Dellavedova", "G"],
    ["Shawn Marion", "G"],
  ],
  "2014-15|Dallas Mavericks": [
    ["Monta Ellis", "G"],
    ["Chandler Parsons", "F"],
    ["Dirk Nowitzki", "F"],
    ["Jameer Nelson", "G"],
    ["Devin Harris", "G"],
    ["Tyson Chandler", "C"],
    ["Brandan Wright", "C"],
    ["Richard Jefferson", "F"],
  ],
  "2014-15|Denver Nuggets": [
    ["Arron Afflalo", "G"],
    ["Ty Lawson", "G"],
    ["Kenneth Faried", "F"],
    ["Timofey Mozgov", "C"],
    ["Wilson Chandler", "F"],
    ["Danilo Gallinari", "F"],
    ["Darrell Arthur", "F"],
    ["Randy Foye", "G"],
  ],
  "2014-15|Detroit Pistons": [
    ["Josh Smith", "F"],
    ["Kentavious Caldwell-Pope", "G"],
    ["Kyle Singler", "F"],
    ["D.J. Augustin", "G"],
    ["Andre Drummond", "C"],
    ["Caron Butler", "F"],
    ["Joel Anthony", "C"],
    ["Brandon Jennings", "G"],
  ],
  "2014-15|Golden State Warriors": [
    ["Klay Thompson", "G"],
    ["Stephen Curry", "G"],
    ["Draymond Green", "F"],
    ["Andre Iguodala", "F"],
    ["Harrison Barnes", "F"],
    ["Andrew Bogut", "C"],
    ["Marreese Speights", "C"],
    ["Leandro Barbosa", "G"],
  ],
  "2014-15|Houston Rockets": [
    ["Patrick Beverley", "G"],
    ["James Harden", "G"],
    ["Terrence Jones", "F"],
    ["Trevor Ariza", "F"],
    ["Tarik Black", "C"],
    ["Jason Terry", "G"],
    ["Dwight Howard", "C"],
    ["Kostas Papanikolaou", "F"],
  ],
  "2014-15|Indiana Pacers": [
    ["Donald Sloan", "G"],
    ["CJ Miles", "G"],
    ["Roy Hibbert", "C"],
    ["Chris Copeland", "F"],
    ["Luis Scola", "F"],
    ["Solomon Hill", "F"],
    ["Lavoy Allen", "C"],
    ["Rodney Stuckey", "G"],
  ],
  "2014-15|LA Clippers": [
    ["Blake Griffin", "F"],
    ["Chris Paul", "G"],
    ["DeAndre Jordan", "C"],
    ["JJ Redick", "G"],
    ["Jamal Crawford", "F"],
    ["Matt Barnes", "F"],
    ["Spencer Hawes", "F"],
    ["Chris Douglas-Roberts", "C"],
  ],
  "2014-15|Los Angeles Lakers": [
    ["Jeremy Lin", "G"],
    ["Kobe Bryant", "G"],
    ["Carlos Boozer", "F"],
    ["Ronnie Price", "G"],
    ["Jordan Hill", "C"],
    ["Wesley Johnson", "F"],
    ["Ed Davis", "F"],
    ["Jordan Clarkson", "G"],
  ],
  "2014-15|Memphis Grizzlies": [
    ["Marc Gasol", "C"],
    ["Courtney Lee", "G"],
    ["Zach Randolph", "F"],
    ["Mike Conley", "G"],
    ["Tony Allen", "F"],
    ["Jon Leuer", "F"],
    ["Vince Carter", "F"],
    ["Beno Udrih", "G"],
  ],
  "2014-15|Miami Heat": [
    ["Chris Bosh", "C"],
    ["Shawne Williams", "F"],
    ["Dwyane Wade", "G"],
    ["Luol Deng", "F"],
    ["Norris Cole", "G"],
    ["Mario Chalmers", "G"],
    ["Chris Andersen", "F"],
    ["Shabazz Napier", "G"],
  ],
  "2014-15|Milwaukee Bucks": [
    ["Brandon Knight", "G"],
    ["Jabari Parker", "F"],
    ["Khris Middleton", "G"],
    ["Jared Dudley", "F"],
    ["Larry Sanders", "C"],
    ["O.J. Mayo", "G"],
    ["Giannis Antetokounmpo", "F"],
    ["Zaza Pachulia", "C"],
  ],
  "2014-15|Minnesota Timberwolves": [
    ["Ricky Rubio", "G"],
    ["Thaddeus Young", "F"],
    ["Nikola Pekovic", "C"],
    ["Corey Brewer", "G"],
    ["Mo Williams", "G"],
    ["Shabazz Muhammad", "F"],
    ["Gorgui Dieng", "C"],
    ["Andrew Wiggins", "F"],
  ],
  "2014-15|New Orleans Pelicans": [
    ["Anthony Davis", "F"],
    ["Tyreke Evans", "G"],
    ["Omer Asik", "C"],
    ["Eric Gordon", "G"],
    ["Jrue Holiday", "G"],
    ["Ryan Anderson", "F"],
    ["Austin Rivers", "G"],
    ["Jimmer Fredette", "C"],
  ],
  "2014-15|New York Knicks": [
    ["Carmelo Anthony", "F"],
    ["Shane Larkin", "G"],
    ["Amar'e Stoudemire", "C"],
    ["JR Smith", "F"],
    ["Quincy Acy", "F"],
    ["Iman Shumpert", "G"],
    ["Samuel Dalembert", "C"],
    ["Tim Hardaway Jr.", "G"],
  ],
  "2014-15|Oklahoma City Thunder": [
    ["Andre Roberson", "G"],
    ["Russell Westbrook", "G"],
    ["Lance Thomas", "F"],
    ["Perry Jones III", "F"],
    ["Serge Ibaka", "F"],
    ["Steven Adams", "C"],
    ["Kendrick Perkins", "C"],
    ["Nick Collison", "C"],
  ],
  "2014-15|Orlando Magic": [
    ["Tobias Harris", "F"],
    ["Nikola Vucevic", "C"],
    ["Evan Fournier", "G"],
    ["Elfrid Payton", "G"],
    ["Aaron Gordon", "F"],
    ["Ben Gordon", "G"],
    ["Kyle O'Quinn", "F"],
    ["Luke Ridnour", "G"],
  ],
  "2014-15|Philadelphia 76ers": [
    ["Tony Wroten", "G"],
    ["Nerlens Noel", "C"],
    ["Chris Johnson", "F"],
    ["Hollis Thompson", "G"],
    ["Alexey Shved", "G"],
    ["Henry Sims", "C"],
    ["KJ McDaniels", "G"],
    ["Brandon Davies", "F"],
  ],
  "2014-15|Phoenix Suns": [
    ["Marcus Morris Sr.", "F"],
    ["Goran Dragic", "G"],
    ["Eric Bledsoe", "G"],
    ["Markieff Morris", "F"],
    ["Miles Plumlee", "C"],
    ["Gerald Green", "G"],
    ["Isaiah Thomas", "G"],
    ["Alex Len", "C"],
  ],
  "2014-15|Portland Trail Blazers": [
    ["Wesley Matthews", "G"],
    ["Nicolas Batum", "F"],
    ["LaMarcus Aldridge", "F"],
    ["Robin Lopez", "C"],
    ["Damian Lillard", "G"],
    ["Chris Kaman", "C"],
    ["Steve Blake", "G"],
    ["CJ McCollum", "G"],
  ],
  "2014-15|Sacramento Kings": [
    ["Darren Collison", "G"],
    ["Rudy Gay", "F"],
    ["DeMarcus Cousins", "C"],
    ["Ben McLemore", "G"],
    ["Nik Stauskas", "F"],
    ["Jason Thompson", "F"],
    ["Carl Landry", "F"],
    ["Omri Casspi", "F"],
  ],
  "2014-15|San Antonio Spurs": [
    ["Tony Parker", "G"],
    ["Danny Green", "G"],
    ["Boris Diaw", "C"],
    ["Marco Belinelli", "F"],
    ["Tim Duncan", "F"],
    ["Manu Ginobili", "G"],
    ["Aron Baynes", "C"],
    ["Cory Joseph", "G"],
  ],
  "2014-15|Toronto Raptors": [
    ["DeMar DeRozan", "G"],
    ["Kyle Lowry", "G"],
    ["Amir Johnson", "F"],
    ["Terrence Ross", "F"],
    ["Patrick Patterson", "F"],
    ["Jonas Valanciunas", "C"],
    ["Tyler Hansbrough", "F"],
    ["Greivis Vasquez", "G"],
  ],
  "2014-15|Utah Jazz": [
    ["Trey Burke", "G"],
    ["Gordon Hayward", "F"],
    ["Alec Burks", "G"],
    ["Derrick Favors", "F"],
    ["Trevor Booker", "F"],
    ["Enes Freedom", "C"],
    ["Rodney Hood", "G"],
    ["Rudy Gobert", "C"],
  ],
  "2014-15|Washington Wizards": [
    ["Marcin Gortat", "C"],
    ["John Wall", "G"],
    ["Drew Gooden", "F"],
    ["Paul Pierce", "F"],
    ["Garrett Temple", "G"],
    ["Otto Porter Jr.", "F"],
    ["Kris Humphries", "F"],
    ["Andre Miller", "G"],
  ],
  "2015-16|Atlanta Hawks": [
    ["Paul Millsap", "F"],
    ["Jeff Teague", "G"],
    ["Al Horford", "C"],
    ["Kyle Korver", "G"],
    ["Dennis Schroder", "G"],
    ["Kent Bazemore", "F"],
    ["Thabo Sefolosha", "F"],
    ["Lamar Patterson", "C"],
  ],
  "2015-16|Boston Celtics": [
    ["Avery Bradley", "G"],
    ["Marcus Smart", "G"],
    ["Jae Crowder", "F"],
    ["Isaiah Thomas", "G"],
    ["Evan Turner", "F"],
    ["David Lee", "F"],
    ["Jared Sullinger", "C"],
    ["Amir Johnson", "F"],
  ],
  "2015-16|Brooklyn Nets": [
    ["Brook Lopez", "C"],
    ["Joe Johnson", "F"],
    ["Bojan Bogdanovic", "F"],
    ["Thaddeus Young", "F"],
    ["Rondae Hollis-Jefferson", "G"],
    ["Shane Larkin", "G"],
    ["Andrea Bargnani", "F"],
    ["Donald Sloan", "G"],
  ],
  "2015-16|Charlotte Hornets": [
    ["Marvin Williams", "F"],
    ["Kemba Walker", "G"],
    ["Nicolas Batum", "G"],
    ["Cody Zeller", "C"],
    ["Jeremy Lin", "G"],
    ["Al Jefferson", "C"],
    ["PJ Hairston", "F"],
    ["Spencer Hawes", "C"],
  ],
  "2015-16|Chicago Bulls": [
    ["Jimmy Butler", "G"],
    ["Derrick Rose", "G"],
    ["Pau Gasol", "C"],
    ["Tony Snell", "F"],
    ["Nikola Mirotic", "F"],
    ["Taj Gibson", "F"],
    ["Joakim Noah", "C"],
    ["Doug McDermott", "F"],
  ],
  "2015-16|Cleveland Cavaliers": [
    ["Mo Williams", "G"],
    ["LeBron James", "F"],
    ["Kevin Love", "F"],
    ["JR Smith", "G"],
    ["Tristan Thompson", "C"],
    ["Timofey Mozgov", "C"],
    ["Matthew Dellavedova", "G"],
    ["Richard Jefferson", "F"],
  ],
  "2015-16|Dallas Mavericks": [
    ["Raymond Felton", "G"],
    ["Wesley Matthews", "G"],
    ["Jeremy Evans", "F"],
    ["Zaza Pachulia", "C"],
    ["J.J. Barea", "G"],
    ["Devin Harris", "G"],
    ["Dirk Nowitzki", "F"],
    ["Deron Williams", "G"],
  ],
  "2015-16|Denver Nuggets": [
    ["Emmanuel Mudiay", "G"],
    ["Danilo Gallinari", "F"],
    ["Kenneth Faried", "F"],
    ["Gary Harris", "G"],
    ["Jameer Nelson", "G"],
    ["Joffrey Lauvergne", "C"],
    ["Will Barton", "F"],
    ["Randy Foye", "G"],
  ],
  "2015-16|Detroit Pistons": [
    ["Andre Drummond", "C"],
    ["Marcus Morris Sr.", "F"],
    ["Kentavious Caldwell-Pope", "G"],
    ["Ersan Ilyasova", "F"],
    ["Reggie Jackson", "G"],
    ["Stanley Johnson", "G"],
    ["Steve Blake", "G"],
    ["Jodie Meeks", "C"],
  ],
  "2015-16|Golden State Warriors": [
    ["Stephen Curry", "G"],
    ["Harrison Barnes", "F"],
    ["Draymond Green", "F"],
    ["Klay Thompson", "G"],
    ["Andre Iguodala", "F"],
    ["Shaun Livingston", "G"],
    ["Leandro Barbosa", "F"],
    ["Andrew Bogut", "C"],
  ],
  "2015-16|Houston Rockets": [
    ["Ty Lawson", "G"],
    ["James Harden", "G"],
    ["Trevor Ariza", "F"],
    ["Corey Brewer", "F"],
    ["Terrence Jones", "F"],
    ["Clint Capela", "F"],
    ["Patrick Beverley", "G"],
    ["Montrezl Harrell", "F"],
  ],
  "2015-16|Indiana Pacers": [
    ["George Hill", "G"],
    ["Paul George", "F"],
    ["CJ Miles", "F"],
    ["Monta Ellis", "G"],
    ["Ian Mahinmi", "C"],
    ["Rodney Stuckey", "G"],
    ["Jordan Hill", "C"],
    ["Chase Budinger", "G"],
  ],
  "2015-16|LA Clippers": [
    ["Blake Griffin", "F"],
    ["Chris Paul", "G"],
    ["JJ Redick", "G"],
    ["DeAndre Jordan", "C"],
    ["Paul Pierce", "F"],
    ["Jamal Crawford", "G"],
    ["Lance Stephenson", "F"],
    ["Josh Smith", "F"],
  ],
  "2015-16|Los Angeles Lakers": [
    ["Julius Randle", "F"],
    ["Jordan Clarkson", "G"],
    ["Kobe Bryant", "F"],
    ["Roy Hibbert", "C"],
    ["Lou Williams", "G"],
    ["D'Angelo Russell", "G"],
    ["Ryan Kelly", "C"],
    ["Nick Young", "G"],
  ],
  "2015-16|Memphis Grizzlies": [
    ["Courtney Lee", "G"],
    ["Zach Randolph", "F"],
    ["Marc Gasol", "C"],
    ["Mike Conley", "G"],
    ["Tony Allen", "G"],
    ["Jeff Green", "F"],
    ["Matt Barnes", "F"],
    ["Brandan Wright", "F"],
  ],
  "2015-16|Miami Heat": [
    ["Chris Bosh", "F"],
    ["Goran Dragic", "G"],
    ["Gerald Green", "F"],
    ["Luol Deng", "F"],
    ["Dwyane Wade", "G"],
    ["Justise Winslow", "F"],
    ["Hassan Whiteside", "C"],
    ["Mario Chalmers", "G"],
  ],
  "2015-16|Milwaukee Bucks": [
    ["Khris Middleton", "G"],
    ["Greg Monroe", "C"],
    ["Michael Carter-Williams", "G"],
    ["Jerryd Bayless", "G"],
    ["Greivis Vasquez", "G"],
    ["Chris Copeland", "F"],
    ["Johnny O'Bryant III", "F"],
    ["Damien Inglis", "G"],
  ],
  "2015-16|Minnesota Timberwolves": [
    ["Ricky Rubio", "G"],
    ["Karl-Anthony Towns", "C"],
    ["Andrew Wiggins", "G"],
    ["Kevin Martin", "G"],
    ["Nemanja Bjelica", "F"],
    ["Gorgui Dieng", "F"],
    ["Zach LaVine", "G"],
    ["Shabazz Muhammad", "F"],
  ],
  "2015-16|New Orleans Pelicans": [
    ["Ish Smith", "G"],
    ["Anthony Davis", "F"],
    ["Eric Gordon", "G"],
    ["Ryan Anderson", "F"],
    ["Alonzo Gee", "F"],
    ["Dante Cunningham", "F"],
    ["Nate Robinson", "G"],
    ["Alexis Ajinca", "F"],
  ],
  "2015-16|New York Knicks": [
    ["Carmelo Anthony", "F"],
    ["Sasha Vujacic", "G"],
    ["Langston Galloway", "G"],
    ["Kristaps Porzingis", "F"],
    ["Jerian Grant", "G"],
    ["Kyle O'Quinn", "F"],
    ["Derrick Williams", "F"],
    ["Robin Lopez", "C"],
  ],
  "2015-16|Oklahoma City Thunder": [
    ["Russell Westbrook", "G"],
    ["Kevin Durant", "F"],
    ["Serge Ibaka", "F"],
    ["Steven Adams", "C"],
    ["Enes Freedom", "F"],
    ["Anthony Morrow", "G"],
    ["Dion Waiters", "G"],
    ["Andre Roberson", "G"],
  ],
  "2015-16|Orlando Magic": [
    ["Victor Oladipo", "G"],
    ["Elfrid Payton", "G"],
    ["Tobias Harris", "F"],
    ["Nikola Vucevic", "C"],
    ["Evan Fournier", "F"],
    ["Mario Hezonja", "G"],
    ["C.J. Watson", "G"],
    ["Aaron Gordon", "F"],
  ],
  "2015-16|Philadelphia 76ers": [
    ["Jahlil Okafor", "C"],
    ["Isaiah Canaan", "G"],
    ["Hollis Thompson", "F"],
    ["Nerlens Noel", "F"],
    ["T.J. McConnell", "G"],
    ["JaKarr Sampson", "F"],
    ["Jerami Grant", "F"],
    ["Richaun Holmes", "F"],
  ],
  "2015-16|Phoenix Suns": [
    ["Brandon Knight", "G"],
    ["Eric Bledsoe", "G"],
    ["Devin Booker", "G"],
    ["Jon Leuer", "F"],
    ["T.J. Warren", "F"],
    ["Mirza Teletovic", "F"],
    ["Archie Goodwin", "G"],
    ["Tyson Chandler", "C"],
  ],
  "2015-16|Portland Trail Blazers": [
    ["CJ McCollum", "G"],
    ["Damian Lillard", "G"],
    ["Meyers Leonard", "F"],
    ["Al-Farouq Aminu", "F"],
    ["Ed Davis", "C"],
    ["Allen Crabbe", "G"],
    ["Mason Plumlee", "C"],
    ["Maurice Harkless", "F"],
  ],
  "2015-16|Sacramento Kings": [
    ["DeMarcus Cousins", "C"],
    ["Marco Belinelli", "G"],
    ["Rudy Gay", "F"],
    ["Darren Collison", "G"],
    ["Rajon Rondo", "G"],
    ["Kosta Koufos", "C"],
    ["Omri Casspi", "F"],
    ["Ben McLemore", "G"],
  ],
  "2015-16|San Antonio Spurs": [
    ["Kawhi Leonard", "F"],
    ["LaMarcus Aldridge", "F"],
    ["Danny Green", "G"],
    ["Tim Duncan", "C"],
    ["Tony Parker", "G"],
    ["Patty Mills", "G"],
    ["Boris Diaw", "F"],
    ["Manu Ginobili", "G"],
  ],
  "2015-16|Toronto Raptors": [
    ["DeMarre Carroll", "F"],
    ["Kyle Lowry", "G"],
    ["DeMar DeRozan", "G"],
    ["Jonas Valanciunas", "C"],
    ["Cory Joseph", "G"],
    ["Patrick Patterson", "F"],
    ["Luis Scola", "F"],
    ["Bismack Biyombo", "C"],
  ],
  "2015-16|Utah Jazz": [
    ["Rudy Gobert", "C"],
    ["Gordon Hayward", "F"],
    ["Derrick Favors", "F"],
    ["Rodney Hood", "G"],
    ["Raul Neto", "G"],
    ["Alec Burks", "G"],
    ["Joe Ingles", "F"],
    ["Trey Burke", "C"],
  ],
  "2015-16|Washington Wizards": [
    ["John Wall", "G"],
    ["Bradley Beal", "G"],
    ["Otto Porter Jr.", "F"],
    ["Marcin Gortat", "C"],
    ["Kris Humphries", "F"],
    ["Drew Gooden", "C"],
    ["Gary Neal", "G"],
    ["Ramon Sessions", "G"],
  ],
  "2016-17|Atlanta Hawks": [
    ["Paul Millsap", "F"],
    ["Dwight Howard", "C"],
    ["Kent Bazemore", "G"],
    ["Mike Muscala", "F"],
    ["Dennis Schroder", "G"],
    ["Tim Hardaway Jr.", "G"],
    ["Thabo Sefolosha", "F"],
    ["Kyle Korver", "G"],
  ],
  "2016-17|Boston Celtics": [
    ["Avery Bradley", "G"],
    ["Isaiah Thomas", "G"],
    ["Jae Crowder", "F"],
    ["Terry Rozier", "F"],
    ["Al Horford", "C"],
    ["Amir Johnson", "F"],
    ["Jaylen Brown", "G"],
    ["Jonas Jerebko", "F"],
  ],
  "2016-17|Brooklyn Nets": [
    ["Jeremy Lin", "G"],
    ["Justin Hamilton", "C"],
    ["Joe Harris", "G"],
    ["Trevor Booker", "F"],
    ["Rondae Hollis-Jefferson", "F"],
    ["Bojan Bogdanovic", "F"],
    ["Sean Kilpatrick", "G"],
    ["Luis Scola", "C"],
  ],
  "2016-17|Charlotte Hornets": [
    ["Kemba Walker", "G"],
    ["Michael Kidd-Gilchrist", "F"],
    ["Nicolas Batum", "G"],
    ["Roy Hibbert", "C"],
    ["Marvin Williams", "F"],
    ["Marco Belinelli", "G"],
    ["Cody Zeller", "C"],
    ["Ramon Sessions", "G"],
  ],
  "2016-17|Chicago Bulls": [
    ["Jimmy Butler", "F"],
    ["Rajon Rondo", "G"],
    ["Dwyane Wade", "G"],
    ["Nikola Mirotic", "F"],
    ["Taj Gibson", "F"],
    ["Robin Lopez", "C"],
    ["Doug McDermott", "F"],
    ["Michael Carter-Williams", "G"],
  ],
  "2016-17|Cleveland Cavaliers": [
    ["LeBron James", "F"],
    ["Kyrie Irving", "G"],
    ["Richard Jefferson", "F"],
    ["JR Smith", "G"],
    ["Kevin Love", "F"],
    ["Mike Dunleavy", "F"],
    ["Tristan Thompson", "C"],
    ["Channing Frye", "F"],
  ],
  "2016-17|Dallas Mavericks": [
    ["Deron Williams", "G"],
    ["Wesley Matthews", "G"],
    ["J.J. Barea", "G"],
    ["Dirk Nowitzki", "C"],
    ["Harrison Barnes", "F"],
    ["Andrew Bogut", "C"],
    ["Justin Anderson", "G"],
    ["Dwight Powell", "F"],
  ],
  "2016-17|Denver Nuggets": [
    ["Danilo Gallinari", "F"],
    ["Will Barton", "G"],
    ["Wilson Chandler", "F"],
    ["Kenneth Faried", "F"],
    ["Emmanuel Mudiay", "G"],
    ["Jusuf Nurkic", "C"],
    ["Nikola Jokic", "C"],
    ["Jameer Nelson", "G"],
  ],
  "2016-17|Detroit Pistons": [
    ["Kentavious Caldwell-Pope", "G"],
    ["Tobias Harris", "F"],
    ["Ish Smith", "G"],
    ["Marcus Morris Sr.", "F"],
    ["Andre Drummond", "C"],
    ["Jon Leuer", "F"],
    ["Aron Baynes", "C"],
    ["Beno Udrih", "G"],
  ],
  "2016-17|Golden State Warriors": [
    ["Kevin Durant", "F"],
    ["Stephen Curry", "G"],
    ["Klay Thompson", "G"],
    ["Draymond Green", "F"],
    ["Andre Iguodala", "G"],
    ["Zaza Pachulia", "C"],
    ["Ian Clark", "F"],
    ["Shaun Livingston", "G"],
  ],
  "2016-17|Houston Rockets": [
    ["James Harden", "G"],
    ["Eric Gordon", "G"],
    ["Ryan Anderson", "F"],
    ["Trevor Ariza", "F"],
    ["Clint Capela", "C"],
    ["Nene Hilario", "C"],
    ["Corey Brewer", "G"],
    ["Sam Dekker", "F"],
  ],
  "2016-17|Indiana Pacers": [
    ["Monta Ellis", "G"],
    ["Paul George", "F"],
    ["Myles Turner", "C"],
    ["Jeff Teague", "G"],
    ["Thaddeus Young", "F"],
    ["Rodney Stuckey", "G"],
    ["CJ Miles", "G"],
    ["Al Jefferson", "C"],
  ],
  "2016-17|LA Clippers": [
    ["Blake Griffin", "F"],
    ["Chris Paul", "G"],
    ["JJ Redick", "G"],
    ["DeAndre Jordan", "C"],
    ["Austin Rivers", "G"],
    ["Jamal Crawford", "G"],
    ["Luc Mbah a Moute", "F"],
    ["Raymond Felton", "G"],
  ],
  "2016-17|Los Angeles Lakers": [
    ["Julius Randle", "F"],
    ["D'Angelo Russell", "G"],
    ["Luol Deng", "F"],
    ["Nick Young", "G"],
    ["Jordan Clarkson", "G"],
    ["Brandon Ingram", "F"],
    ["Larry Nance Jr.", "C"],
    ["Timofey Mozgov", "C"],
  ],
  "2016-17|Memphis Grizzlies": [
    ["Andrew Harrison", "G"],
    ["Marc Gasol", "C"],
    ["Mike Conley", "G"],
    ["JaMychal Green", "F"],
    ["James Ennis III", "F"],
    ["Vince Carter", "F"],
    ["Zach Randolph", "C"],
    ["Wade Baldwin IV", "G"],
  ],
  "2016-17|Miami Heat": [
    ["Justise Winslow", "F"],
    ["Dion Waiters", "G"],
    ["Hassan Whiteside", "C"],
    ["Goran Dragic", "G"],
    ["Tyler Johnson", "F"],
    ["James Johnson", "F"],
    ["Rodney McGruder", "F"],
    ["Luke Babbitt", "F"],
  ],
  "2016-17|Milwaukee Bucks": [
    ["Giannis Antetokounmpo", "F"],
    ["Jabari Parker", "F"],
    ["Greg Monroe", "F"],
    ["Matthew Dellavedova", "G"],
    ["Mirza Teletovic", "F"],
    ["Malcolm Brogdon", "G"],
    ["Michael Beasley", "F"],
    ["Jason Terry", "C"],
  ],
  "2016-17|Minnesota Timberwolves": [
    ["Karl-Anthony Towns", "C"],
    ["Andrew Wiggins", "F"],
    ["Gorgui Dieng", "F"],
    ["Zach LaVine", "G"],
    ["Ricky Rubio", "G"],
    ["Nemanja Bjelica", "F"],
    ["Kris Dunn", "G"],
    ["Brandon Rush", "G"],
  ],
  "2016-17|New Orleans Pelicans": [
    ["Anthony Davis", "F"],
    ["Tim Frazier", "G"],
    ["E'Twaun Moore", "G"],
    ["Solomon Hill", "F"],
    ["Lance Stephenson", "G"],
    ["Terrence Jones", "F"],
    ["Buddy Hield", "G"],
    ["Omer Asik", "C"],
  ],
  "2016-17|New York Knicks": [
    ["Kristaps Porzingis", "F"],
    ["Carmelo Anthony", "F"],
    ["Derrick Rose", "G"],
    ["Justin Holiday", "F"],
    ["Brandon Jennings", "G"],
    ["Courtney Lee", "G"],
    ["Joakim Noah", "C"],
    ["Lance Thomas", "F"],
  ],
  "2016-17|Oklahoma City Thunder": [
    ["Russell Westbrook", "G"],
    ["Steven Adams", "C"],
    ["Andre Roberson", "F"],
    ["Victor Oladipo", "G"],
    ["Enes Freedom", "C"],
    ["Kyle Singler", "F"],
    ["Ersan Ilyasova", "C"],
    ["Domantas Sabonis", "F"],
  ],
  "2016-17|Orlando Magic": [
    ["Evan Fournier", "G"],
    ["Elfrid Payton", "G"],
    ["Serge Ibaka", "F"],
    ["Nikola Vucevic", "C"],
    ["Aaron Gordon", "F"],
    ["Jeff Green", "F"],
    ["D.J. Augustin", "G"],
    ["Mario Hezonja", "F"],
  ],
  "2016-17|Philadelphia 76ers": [
    ["Robert Covington", "F"],
    ["Sergio Rodriguez", "G"],
    ["Dario Saric", "F"],
    ["Gerald Henderson", "G"],
    ["Nik Stauskas", "G"],
    ["Joel Embiid", "C"],
    ["Jerami Grant", "C"],
    ["T.J. McConnell", "G"],
  ],
  "2016-17|Phoenix Suns": [
    ["T.J. Warren", "F"],
    ["Eric Bledsoe", "G"],
    ["Brandon Knight", "G"],
    ["Jared Dudley", "F"],
    ["Devin Booker", "G"],
    ["Alex Len", "C"],
    ["Tyson Chandler", "C"],
    ["Marquese Chriss", "F"],
  ],
  "2016-17|Portland Trail Blazers": [
    ["Damian Lillard", "G"],
    ["CJ McCollum", "G"],
    ["Allen Crabbe", "G"],
    ["Al-Farouq Aminu", "F"],
    ["Evan Turner", "F"],
    ["Ed Davis", "F"],
    ["Maurice Harkless", "F"],
    ["Noah Vonleh", "F"],
  ],
  "2016-17|Sacramento Kings": [
    ["Ty Lawson", "G"],
    ["Rudy Gay", "F"],
    ["Matt Barnes", "F"],
    ["Arron Afflalo", "G"],
    ["DeMarcus Cousins", "F"],
    ["Willie Cauley-Stein", "C"],
    ["Garrett Temple", "F"],
    ["Ben McLemore", "G"],
  ],
  "2016-17|San Antonio Spurs": [
    ["LaMarcus Aldridge", "F"],
    ["Kawhi Leonard", "F"],
    ["Jonathon Simmons", "G"],
    ["Tony Parker", "G"],
    ["Kyle Anderson", "G"],
    ["Manu Ginobili", "G"],
    ["Pau Gasol", "C"],
    ["Patty Mills", "G"],
  ],
  "2016-17|Toronto Raptors": [
    ["Kyle Lowry", "G"],
    ["Jonas Valanciunas", "C"],
    ["DeMar DeRozan", "G"],
    ["DeMarre Carroll", "F"],
    ["Patrick Patterson", "F"],
    ["Pascal Siakam", "F"],
    ["Cory Joseph", "G"],
    ["Terrence Ross", "C"],
  ],
  "2016-17|Utah Jazz": [
    ["Rudy Gobert", "C"],
    ["George Hill", "G"],
    ["Rodney Hood", "G"],
    ["Boris Diaw", "F"],
    ["Joe Johnson", "F"],
    ["Trey Lyles", "F"],
    ["Shelvin Mack", "G"],
    ["Joe Ingles", "G"],
  ],
  "2016-17|Washington Wizards": [
    ["Marcin Gortat", "C"],
    ["John Wall", "G"],
    ["Markieff Morris", "F"],
    ["Otto Porter Jr.", "F"],
    ["Bradley Beal", "G"],
    ["Kelly Oubre Jr.", "F"],
    ["Marcus Thornton", "G"],
    ["Andrew Nicholson", "F"],
  ],
  "2017-18|Atlanta Hawks": [
    ["Dennis Schroder", "G"],
    ["Kent Bazemore", "G"],
    ["Taurean Prince", "F"],
    ["Marco Belinelli", "G"],
    ["Dewayne Dedmon", "C"],
    ["Ersan Ilyasova", "F"],
    ["John Collins", "F"],
    ["DeAndre' Bembry", "G"],
  ],
  "2017-18|Boston Celtics": [
    ["Jaylen Brown", "G"],
    ["Kyrie Irving", "G"],
    ["Jayson Tatum", "F"],
    ["Marcus Smart", "G"],
    ["Al Horford", "F"],
    ["Terry Rozier", "G"],
    ["Aron Baynes", "C"],
    ["Semi Ojeleye", "F"],
  ],
  "2017-18|Brooklyn Nets": [
    ["D'Angelo Russell", "G"],
    ["Trevor Booker", "F"],
    ["Caris LeVert", "G"],
    ["Rondae Hollis-Jefferson", "F"],
    ["DeMarre Carroll", "F"],
    ["Allen Crabbe", "G"],
    ["Jeremy Lin", "G"],
    ["Spencer Dinwiddie", "G"],
  ],
  "2017-18|Charlotte Hornets": [
    ["Kemba Walker", "G"],
    ["Dwight Howard", "C"],
    ["Jeremy Lamb", "G"],
    ["Marvin Williams", "F"],
    ["Cody Zeller", "C"],
    ["Frank Kaminsky", "F"],
    ["Malik Monk", "F"],
    ["Dwayne Bacon", "F"],
  ],
  "2017-18|Chicago Bulls": [
    ["Justin Holiday", "G"],
    ["Lauri Markkanen", "F"],
    ["Robin Lopez", "C"],
    ["Jerian Grant", "G"],
    ["Denzel Valentine", "F"],
    ["Paul Zipser", "F"],
    ["Cristiano Felicio", "C"],
    ["Kay Felder", "G"],
  ],
  "2017-18|Cleveland Cavaliers": [
    ["LeBron James", "F"],
    ["Jae Crowder", "F"],
    ["Derrick Rose", "G"],
    ["Dwyane Wade", "G"],
    ["Kevin Love", "C"],
    ["JR Smith", "G"],
    ["Tristan Thompson", "C"],
    ["Jeff Green", "F"],
  ],
  "2017-18|Dallas Mavericks": [
    ["Harrison Barnes", "F"],
    ["Wesley Matthews", "G"],
    ["Yogi Ferrell", "G"],
    ["Dennis Smith Jr.", "G"],
    ["Dirk Nowitzki", "C"],
    ["Nerlens Noel", "C"],
    ["J.J. Barea", "G"],
    ["Devin Harris", "G"],
  ],
  "2017-18|Denver Nuggets": [
    ["Gary Harris", "G"],
    ["Nikola Jokic", "C"],
    ["Wilson Chandler", "F"],
    ["Paul Millsap", "F"],
    ["Will Barton", "F"],
    ["Jamal Murray", "G"],
    ["Emmanuel Mudiay", "G"],
    ["Mason Plumlee", "C"],
  ],
  "2017-18|Detroit Pistons": [
    ["Stanley Johnson", "F"],
    ["Tobias Harris", "F"],
    ["Reggie Jackson", "G"],
    ["Langston Galloway", "G"],
    ["Avery Bradley", "G"],
    ["Andre Drummond", "C"],
    ["Ish Smith", "G"],
    ["Jon Leuer", "F"],
  ],
  "2017-18|Golden State Warriors": [
    ["Klay Thompson", "G"],
    ["Kevin Durant", "F"],
    ["Stephen Curry", "G"],
    ["Draymond Green", "F"],
    ["Nick Young", "G"],
    ["Patrick McCaw", "G"],
    ["Shaun Livingston", "G"],
    ["Jordan Bell", "F"],
  ],
  "2017-18|Houston Rockets": [
    ["Trevor Ariza", "F"],
    ["James Harden", "G"],
    ["Ryan Anderson", "F"],
    ["Chris Paul", "G"],
    ["Eric Gordon", "G"],
    ["P.J. Tucker", "F"],
    ["Luc Mbah a Moute", "F"],
    ["Clint Capela", "C"],
  ],
  "2017-18|Indiana Pacers": [
    ["Myles Turner", "C"],
    ["Thaddeus Young", "F"],
    ["Darren Collison", "G"],
    ["Bojan Bogdanovic", "F"],
    ["Cory Joseph", "G"],
    ["Victor Oladipo", "G"],
    ["Lance Stephenson", "G"],
    ["Domantas Sabonis", "C"],
  ],
  "2017-18|LA Clippers": [
    ["Blake Griffin", "F"],
    ["Danilo Gallinari", "F"],
    ["DeAndre Jordan", "C"],
    ["Austin Rivers", "G"],
    ["Lou Williams", "G"],
    ["Patrick Beverley", "G"],
    ["Milos Teodosic", "G"],
    ["Wesley Johnson", "F"],
  ],
  "2017-18|Los Angeles Lakers": [
    ["Brandon Ingram", "F"],
    ["Larry Nance Jr.", "F"],
    ["Lonzo Ball", "G"],
    ["Brook Lopez", "C"],
    ["Jordan Clarkson", "G"],
    ["Kyle Kuzma", "F"],
    ["Julius Randle", "F"],
    ["Corey Brewer", "F"],
  ],
  "2017-18|Memphis Grizzlies": [
    ["Mike Conley", "G"],
    ["Dillon Brooks", "F"],
    ["Marc Gasol", "C"],
    ["Brandan Wright", "F"],
    ["Mario Chalmers", "G"],
    ["Tyreke Evans", "G"],
    ["Jarell Martin", "F"],
    ["Andrew Harrison", "G"],
  ],
  "2017-18|Miami Heat": [
    ["Dion Waiters", "G"],
    ["Hassan Whiteside", "C"],
    ["Josh Richardson", "F"],
    ["Goran Dragic", "G"],
    ["Justise Winslow", "F"],
    ["Tyler Johnson", "G"],
    ["Kelly Olynyk", "F"],
    ["James Johnson", "F"],
  ],
  "2017-18|Milwaukee Bucks": [
    ["Khris Middleton", "F"],
    ["Malcolm Brogdon", "G"],
    ["Giannis Antetokounmpo", "F"],
    ["Tony Snell", "G"],
    ["Matthew Dellavedova", "G"],
    ["John Henson", "C"],
    ["Greg Monroe", "C"],
    ["Thon Maker", "C"],
  ],
  "2017-18|Minnesota Timberwolves": [
    ["Jimmy Butler", "G"],
    ["Karl-Anthony Towns", "C"],
    ["Andrew Wiggins", "F"],
    ["Taj Gibson", "F"],
    ["Jeff Teague", "G"],
    ["Jamal Crawford", "G"],
    ["Tyus Jones", "G"],
    ["Shabazz Muhammad", "G"],
  ],
  "2017-18|New Orleans Pelicans": [
    ["Anthony Davis", "F"],
    ["Jrue Holiday", "G"],
    ["DeMarcus Cousins", "C"],
    ["E'Twaun Moore", "F"],
    ["Dante Cunningham", "F"],
    ["Ian Clark", "G"],
    ["Darius Miller", "F"],
    ["Jordan Crawford", "G"],
  ],
  "2017-18|New York Knicks": [
    ["Kristaps Porzingis", "F"],
    ["Courtney Lee", "G"],
    ["Tim Hardaway Jr.", "F"],
    ["Doug McDermott", "F"],
    ["Ron Baker", "G"],
    ["Enes Freedom", "C"],
    ["Kyle O'Quinn", "C"],
    ["Ramon Sessions", "G"],
  ],
  "2017-18|Oklahoma City Thunder": [
    ["Paul George", "F"],
    ["Carmelo Anthony", "F"],
    ["Russell Westbrook", "G"],
    ["Steven Adams", "C"],
    ["Alex Abrines", "G"],
    ["Andre Roberson", "G"],
    ["Jerami Grant", "F"],
    ["Raymond Felton", "G"],
  ],
  "2017-18|Orlando Magic": [
    ["Evan Fournier", "G"],
    ["Aaron Gordon", "F"],
    ["Elfrid Payton", "G"],
    ["Nikola Vucevic", "C"],
    ["Terrence Ross", "G"],
    ["Jonathon Simmons", "F"],
    ["Jonathan Isaac", "F"],
    ["D.J. Augustin", "G"],
  ],
  "2017-18|Philadelphia 76ers": [
    ["Ben Simmons", "G"],
    ["JJ Redick", "G"],
    ["Robert Covington", "F"],
    ["Jerryd Bayless", "G"],
    ["Joel Embiid", "C"],
    ["Dario Saric", "F"],
    ["Timothe Luwawu-Cabarrot", "G"],
    ["Markelle Fultz", "G"],
  ],
  "2017-18|Phoenix Suns": [
    ["Josh Jackson", "F"],
    ["Eric Bledsoe", "G"],
    ["T.J. Warren", "F"],
    ["Devin Booker", "G"],
    ["Tyson Chandler", "C"],
    ["Troy Daniels", "G"],
    ["Dragan Bender", "F"],
    ["Tyler Ulis", "G"],
  ],
  "2017-18|Portland Trail Blazers": [
    ["Pat Connaughton", "F"],
    ["Damian Lillard", "G"],
    ["Al-Farouq Aminu", "F"],
    ["Maurice Harkless", "F"],
    ["Evan Turner", "F"],
    ["Jusuf Nurkic", "C"],
    ["Shabazz Napier", "G"],
    ["Caleb Swanigan", "F"],
  ],
  "2017-18|Sacramento Kings": [
    ["Buddy Hield", "G"],
    ["Skal Labissiere", "F"],
    ["George Hill", "G"],
    ["Willie Cauley-Stein", "C"],
    ["Garrett Temple", "F"],
    ["De'Aaron Fox", "G"],
    ["Justin Jackson", "F"],
    ["Kosta Koufos", "C"],
  ],
  "2017-18|San Antonio Spurs": [
    ["LaMarcus Aldridge", "F"],
    ["Danny Green", "G"],
    ["Kyle Anderson", "F"],
    ["Pau Gasol", "C"],
    ["Dejounte Murray", "G"],
    ["Rudy Gay", "F"],
    ["Patty Mills", "G"],
    ["Manu Ginobili", "G"],
  ],
  "2017-18|Toronto Raptors": [
    ["DeMar DeRozan", "G"],
    ["Kyle Lowry", "G"],
    ["Jonas Valanciunas", "C"],
    ["Norman Powell", "F"],
    ["Serge Ibaka", "F"],
    ["Delon Wright", "G"],
    ["CJ Miles", "F"],
    ["Jakob Poeltl", "C"],
  ],
  "2017-18|Utah Jazz": [
    ["Rudy Gobert", "C"],
    ["Joe Ingles", "F"],
    ["Ricky Rubio", "G"],
    ["Derrick Favors", "F"],
    ["Donovan Mitchell", "G"],
    ["Thabo Sefolosha", "F"],
    ["Joe Johnson", "F"],
    ["Rodney Hood", "G"],
  ],
  "2017-18|Washington Wizards": [
    ["John Wall", "G"],
    ["Bradley Beal", "G"],
    ["Marcin Gortat", "C"],
    ["Otto Porter Jr.", "F"],
    ["Kelly Oubre Jr.", "F"],
    ["Jodie Meeks", "G"],
    ["Mike Scott", "F"],
    ["Ian Mahinmi", "C"],
  ],
  "2018-19|Atlanta Hawks": [
    ["Trae Young", "G"],
    ["Taurean Prince", "F"],
    ["Kent Bazemore", "G"],
    ["Vince Carter", "F"],
    ["DeAndre' Bembry", "F"],
    ["Alex Len", "C"],
    ["Alex Poythress", "F"],
    ["Tyler Dorsey", "F"],
  ],
  "2018-19|Boston Celtics": [
    ["Al Horford", "C"],
    ["Kyrie Irving", "G"],
    ["Jayson Tatum", "F"],
    ["Jaylen Brown", "G"],
    ["Terry Rozier", "G"],
    ["Marcus Smart", "G"],
    ["Gordon Hayward", "F"],
    ["Marcus Morris Sr.", "F"],
  ],
  "2018-19|Brooklyn Nets": [
    ["Joe Harris", "F"],
    ["Jared Dudley", "F"],
    ["Caris LeVert", "G"],
    ["Spencer Dinwiddie", "G"],
    ["Jarrett Allen", "C"],
    ["D'Angelo Russell", "G"],
    ["Ed Davis", "C"],
    ["Treveon Graham", "F"],
  ],
  "2018-19|Charlotte Hornets": [
    ["Kemba Walker", "G"],
    ["Malik Monk", "G"],
    ["Nicolas Batum", "F"],
    ["Marvin Williams", "F"],
    ["Michael Kidd-Gilchrist", "F"],
    ["Cody Zeller", "C"],
    ["Jeremy Lamb", "G"],
    ["Tony Parker", "G"],
  ],
  "2018-19|Chicago Bulls": [
    ["Bobby Portis", "F"],
    ["Zach LaVine", "G"],
    ["Antonio Blakeney", "G"],
    ["Ryan Arcidiacono", "G"],
    ["Justin Holiday", "F"],
    ["Jabari Parker", "F"],
    ["Cameron Payne", "G"],
    ["Wendell Carter Jr.", "C"],
  ],
  "2018-19|Cleveland Cavaliers": [
    ["Kevin Love", "F"],
    ["Cedi Osman", "F"],
    ["George Hill", "G"],
    ["Tristan Thompson", "C"],
    ["Rodney Hood", "G"],
    ["Jordan Clarkson", "G"],
    ["Collin Sexton", "G"],
    ["Sam Dekker", "F"],
  ],
  "2018-19|Dallas Mavericks": [
    ["Wesley Matthews", "G"],
    ["Luka Doncic", "G"],
    ["DeAndre Jordan", "C"],
    ["Dorian Finney-Smith", "F"],
    ["Dennis Smith Jr.", "G"],
    ["J.J. Barea", "G"],
    ["Jalen Brunson", "G"],
    ["Dwight Powell", "C"],
  ],
  "2018-19|Denver Nuggets": [
    ["Will Barton", "F"],
    ["Gary Harris", "G"],
    ["Nikola Jokic", "C"],
    ["Jamal Murray", "G"],
    ["Paul Millsap", "F"],
    ["Trey Lyles", "F"],
    ["Monte Morris", "G"],
    ["Juancho Hernangomez", "F"],
  ],
  "2018-19|Detroit Pistons": [
    ["Reggie Jackson", "G"],
    ["Blake Griffin", "F"],
    ["Langston Galloway", "G"],
    ["Andre Drummond", "C"],
    ["Ish Smith", "G"],
    ["Glenn Robinson III", "F"],
    ["Luke Kennard", "F"],
    ["Bruce Brown", "G"],
  ],
  "2018-19|Golden State Warriors": [
    ["Kevin Durant", "F"],
    ["Stephen Curry", "G"],
    ["Klay Thompson", "G"],
    ["Draymond Green", "F"],
    ["Damian Jones", "C"],
    ["Kevon Looney", "C"],
    ["Shaun Livingston", "G"],
    ["Quinn Cook", "G"],
  ],
  "2018-19|Houston Rockets": [
    ["James Harden", "G"],
    ["P.J. Tucker", "F"],
    ["Chris Paul", "G"],
    ["Eric Gordon", "F"],
    ["Carmelo Anthony", "F"],
    ["Clint Capela", "C"],
    ["James Ennis III", "F"],
    ["Michael Carter-Williams", "F"],
  ],
  "2018-19|Indiana Pacers": [
    ["Domantas Sabonis", "C"],
    ["Cory Joseph", "G"],
    ["Thaddeus Young", "F"],
    ["Bojan Bogdanovic", "F"],
    ["Victor Oladipo", "G"],
    ["Doug McDermott", "F"],
    ["Tyreke Evans", "G"],
    ["Darren Collison", "G"],
  ],
  "2018-19|LA Clippers": [
    ["Tobias Harris", "F"],
    ["Danilo Gallinari", "F"],
    ["Shai Gilgeous-Alexander", "G"],
    ["Avery Bradley", "G"],
    ["Lou Williams", "F"],
    ["Patrick Beverley", "G"],
    ["Marcin Gortat", "C"],
    ["Boban Marjanovic", "C"],
  ],
  "2018-19|Los Angeles Lakers": [
    ["LeBron James", "F"],
    ["Rajon Rondo", "G"],
    ["Kyle Kuzma", "F"],
    ["Brandon Ingram", "G"],
    ["Josh Hart", "G"],
    ["Kentavious Caldwell-Pope", "G"],
    ["JaVale McGee", "C"],
    ["Lonzo Ball", "G"],
  ],
  "2018-19|Memphis Grizzlies": [
    ["Marc Gasol", "C"],
    ["Shelvin Mack", "G"],
    ["Mike Conley", "G"],
    ["Jaren Jackson Jr.", "F"],
    ["JaMychal Green", "F"],
    ["Garrett Temple", "G"],
    ["Chandler Parsons", "F"],
    ["MarShon Brooks", "C"],
  ],
  "2018-19|Miami Heat": [
    ["Josh Richardson", "G"],
    ["Hassan Whiteside", "C"],
    ["Goran Dragic", "G"],
    ["Rodney McGruder", "F"],
    ["Dwyane Wade", "G"],
    ["Tyler Johnson", "F"],
    ["Bam Adebayo", "C"],
    ["Derrick Jones Jr.", "F"],
  ],
  "2018-19|Milwaukee Bucks": [
    ["Malcolm Brogdon", "G"],
    ["Giannis Antetokounmpo", "F"],
    ["Eric Bledsoe", "G"],
    ["Khris Middleton", "F"],
    ["Ersan Ilyasova", "F"],
    ["Donte DiVincenzo", "F"],
    ["Brook Lopez", "C"],
    ["John Henson", "C"],
  ],
  "2018-19|Minnesota Timberwolves": [
    ["Andrew Wiggins", "F"],
    ["Jimmy Butler", "G"],
    ["Jeff Teague", "G"],
    ["Derrick Rose", "G"],
    ["Taj Gibson", "F"],
    ["Gorgui Dieng", "C"],
    ["Karl-Anthony Towns", "C"],
    ["Anthony Tolliver", "F"],
  ],
  "2018-19|New Orleans Pelicans": [
    ["Anthony Davis", "F"],
    ["Jrue Holiday", "G"],
    ["Elfrid Payton", "G"],
    ["E'Twaun Moore", "F"],
    ["Nikola Mirotic", "C"],
    ["Julius Randle", "C"],
    ["Darius Miller", "F"],
    ["Solomon Hill", "F"],
  ],
  "2018-19|New York Knicks": [
    ["Frank Ntilikina", "G"],
    ["Tim Hardaway Jr.", "G"],
    ["Ron Baker", "G"],
    ["Enes Freedom", "C"],
    ["Allonzo Trier", "F"],
    ["Kevin Knox II", "F"],
    ["Trey Burke", "G"],
    ["Mario Hezonja", "F"],
  ],
  "2018-19|Oklahoma City Thunder": [
    ["Paul George", "F"],
    ["Steven Adams", "C"],
    ["Dennis Schroder", "G"],
    ["Jerami Grant", "F"],
    ["Terrance Ferguson", "G"],
    ["Alex Abrines", "G"],
    ["Patrick Patterson", "F"],
    ["Raymond Felton", "G"],
  ],
  "2018-19|Orlando Magic": [
    ["Aaron Gordon", "F"],
    ["Jonathon Simmons", "F"],
    ["Nikola Vucevic", "C"],
    ["Jerian Grant", "G"],
    ["Terrence Ross", "C"],
    ["Mo Bamba", "C"],
    ["Evan Fournier", "G"],
    ["D.J. Augustin", "G"],
  ],
  "2018-19|Philadelphia 76ers": [
    ["Ben Simmons", "G"],
    ["Joel Embiid", "C"],
    ["Robert Covington", "F"],
    ["JJ Redick", "G"],
    ["Markelle Fultz", "G"],
    ["Dario Saric", "F"],
    ["T.J. McConnell", "G"],
    ["Landry Shamet", "G"],
  ],
  "2018-19|Phoenix Suns": [
    ["Trevor Ariza", "F"],
    ["Deandre Ayton", "C"],
    ["Isaiah Canaan", "G"],
    ["Devin Booker", "G"],
    ["Josh Jackson", "F"],
    ["Ryan Anderson", "F"],
    ["T.J. Warren", "F"],
    ["Tyson Chandler", "C"],
  ],
  "2018-19|Portland Trail Blazers": [
    ["Damian Lillard", "G"],
    ["CJ McCollum", "G"],
    ["Nik Stauskas", "F"],
    ["Al-Farouq Aminu", "F"],
    ["Zach Collins", "C"],
    ["Evan Turner", "F"],
    ["Maurice Harkless", "F"],
    ["Jusuf Nurkic", "C"],
  ],
  "2018-19|Sacramento Kings": [
    ["Willie Cauley-Stein", "C"],
    ["De'Aaron Fox", "G"],
    ["Buddy Hield", "G"],
    ["Justin Jackson", "F"],
    ["Yogi Ferrell", "G"],
    ["Nemanja Bjelica", "F"],
    ["Iman Shumpert", "F"],
    ["Marvin Bagley III", "F"],
  ],
  "2018-19|San Antonio Spurs": [
    ["LaMarcus Aldridge", "C"],
    ["DeMar DeRozan", "G"],
    ["Bryn Forbes", "G"],
    ["Patty Mills", "G"],
    ["Rudy Gay", "F"],
    ["Pau Gasol", "C"],
    ["Marco Belinelli", "G"],
    ["Davis Bertans", "F"],
  ],
  "2018-19|Toronto Raptors": [
    ["Kawhi Leonard", "F"],
    ["Kyle Lowry", "G"],
    ["Danny Green", "G"],
    ["Serge Ibaka", "C"],
    ["Fred VanVleet", "G"],
    ["Jonas Valanciunas", "C"],
    ["Pascal Siakam", "F"],
    ["O.G. Anunoby", "F"],
  ],
  "2018-19|Utah Jazz": [
    ["Rudy Gobert", "C"],
    ["Donovan Mitchell", "G"],
    ["Joe Ingles", "F"],
    ["Jae Crowder", "F"],
    ["Dante Exum", "G"],
    ["Derrick Favors", "F"],
    ["Ricky Rubio", "G"],
    ["Alec Burks", "C"],
  ],
  "2018-19|Washington Wizards": [
    ["John Wall", "G"],
    ["Otto Porter Jr.", "F"],
    ["Jeff Green", "F"],
    ["Bradley Beal", "G"],
    ["Austin Rivers", "G"],
    ["Markieff Morris", "F"],
    ["Kelly Oubre Jr.", "F"],
    ["Jason Smith", "C"],
  ],
  "2019-20|Atlanta Hawks": [
    ["Trae Young", "G"],
    ["John Collins", "F"],
    ["De'Andre Hunter", "F"],
    ["Alex Len", "C"],
    ["DeAndre' Bembry", "G"],
    ["Jabari Parker", "F"],
    ["Cam Reddish", "F"],
    ["Evan Turner", "G"],
  ],
  "2019-20|Boston Celtics": [
    ["Jayson Tatum", "F"],
    ["Gordon Hayward", "F"],
    ["Kemba Walker", "G"],
    ["Marcus Smart", "G"],
    ["Enes Freedom", "C"],
    ["Jaylen Brown", "G"],
    ["Carsen Edwards", "F"],
    ["Robert Williams III", "C"],
  ],
  "2019-20|Brooklyn Nets": [
    ["Taurean Prince", "F"],
    ["Joe Harris", "F"],
    ["Kyrie Irving", "G"],
    ["Caris LeVert", "G"],
    ["Jarrett Allen", "C"],
    ["Spencer Dinwiddie", "G"],
    ["Garrett Temple", "G"],
    ["DeAndre Jordan", "C"],
  ],
  "2019-20|Charlotte Hornets": [
    ["P.J. Washington", "F"],
    ["Cody Zeller", "C"],
    ["Dwayne Bacon", "G"],
    ["Miles Bridges", "F"],
    ["Terry Rozier", "G"],
    ["Devonte' Graham", "G"],
    ["Marvin Williams", "F"],
    ["Malik Monk", "G"],
  ],
  "2019-20|Chicago Bulls": [
    ["Lauri Markkanen", "F"],
    ["Zach LaVine", "G"],
    ["Wendell Carter Jr.", "C"],
    ["Otto Porter Jr.", "F"],
    ["Coby White", "G"],
    ["Thaddeus Young", "F"],
    ["Tomas Satoransky", "G"],
    ["Kris Dunn", "F"],
  ],
  "2019-20|Cleveland Cavaliers": [
    ["Kevin Love", "F"],
    ["Tristan Thompson", "C"],
    ["Darius Garland", "G"],
    ["Collin Sexton", "G"],
    ["Cedi Osman", "F"],
    ["Larry Nance Jr.", "F"],
    ["Jordan Clarkson", "F"],
    ["Matthew Dellavedova", "G"],
  ],
  "2019-20|Dallas Mavericks": [
    ["Luka Doncic", "G"],
    ["Dorian Finney-Smith", "F"],
    ["Kristaps Porzingis", "F"],
    ["Jalen Brunson", "G"],
    ["Maxi Kleber", "F"],
    ["Delon Wright", "G"],
    ["Tim Hardaway Jr.", "G"],
    ["Seth Curry", "G"],
  ],
  "2019-20|Denver Nuggets": [
    ["Gary Harris", "G"],
    ["Jamal Murray", "G"],
    ["Paul Millsap", "F"],
    ["Will Barton", "F"],
    ["Nikola Jokic", "C"],
    ["Jerami Grant", "F"],
    ["Mason Plumlee", "C"],
    ["Torrey Craig", "F"],
  ],
  "2019-20|Detroit Pistons": [
    ["Andre Drummond", "C"],
    ["Tony Snell", "F"],
    ["Bruce Brown", "G"],
    ["Luke Kennard", "G"],
    ["Derrick Rose", "G"],
    ["Markieff Morris", "F"],
    ["Reggie Jackson", "G"],
    ["Langston Galloway", "F"],
  ],
  "2019-20|Golden State Warriors": [
    ["D'Angelo Russell", "G"],
    ["Eric Paschall", "F"],
    ["Glenn Robinson III", "F"],
    ["Stephen Curry", "G"],
    ["Draymond Green", "F"],
    ["Jacob Evans", "G"],
    ["Jordan Poole", "G"],
    ["Marquese Chriss", "C"],
  ],
  "2019-20|Houston Rockets": [
    ["P.J. Tucker", "F"],
    ["James Harden", "G"],
    ["Russell Westbrook", "G"],
    ["Clint Capela", "C"],
    ["Eric Gordon", "G"],
    ["Danuel House Jr.", "F"],
    ["Ben McLemore", "F"],
    ["Austin Rivers", "G"],
  ],
  "2019-20|Indiana Pacers": [
    ["Myles Turner", "C"],
    ["Malcolm Brogdon", "G"],
    ["Domantas Sabonis", "F"],
    ["T.J. Warren", "F"],
    ["Jeremy Lamb", "G"],
    ["Edmond Sumner", "G"],
    ["Justin Holiday", "F"],
    ["T.J. McConnell", "G"],
  ],
  "2019-20|LA Clippers": [
    ["Montrezl Harrell", "C"],
    ["Lou Williams", "G"],
    ["Kawhi Leonard", "F"],
    ["Patrick Beverley", "G"],
    ["Maurice Harkless", "F"],
    ["Landry Shamet", "G"],
    ["JaMychal Green", "F"],
    ["Patrick Patterson", "F"],
  ],
  "2019-20|Los Angeles Lakers": [
    ["Anthony Davis", "F"],
    ["LeBron James", "F"],
    ["Danny Green", "G"],
    ["Kentavious Caldwell-Pope", "G"],
    ["Avery Bradley", "G"],
    ["Dwight Howard", "C"],
    ["JaVale McGee", "C"],
    ["Quinn Cook", "G"],
  ],
  "2019-20|Memphis Grizzlies": [
    ["Jae Crowder", "F"],
    ["Jaren Jackson Jr.", "F"],
    ["Ja Morant", "G"],
    ["Marko Guduric", "F"],
    ["Tyus Jones", "G"],
    ["Brandon Clarke", "F"],
    ["Kyle Anderson", "F"],
    ["Grayson Allen", "C"],
  ],
  "2019-20|Miami Heat": [
    ["Justise Winslow", "F"],
    ["Tyler Herro", "G"],
    ["Kendrick Nunn", "G"],
    ["Goran Dragic", "G"],
    ["Bam Adebayo", "F"],
    ["Duncan Robinson", "G"],
    ["Kelly Olynyk", "C"],
    ["Meyers Leonard", "C"],
  ],
  "2019-20|Milwaukee Bucks": [
    ["Khris Middleton", "F"],
    ["George Hill", "G"],
    ["Wesley Matthews", "G"],
    ["Giannis Antetokounmpo", "F"],
    ["Brook Lopez", "C"],
    ["Ersan Ilyasova", "F"],
    ["Pat Connaughton", "F"],
    ["Robin Lopez", "C"],
  ],
  "2019-20|Minnesota Timberwolves": [
    ["Karl-Anthony Towns", "C"],
    ["Andrew Wiggins", "G"],
    ["Treveon Graham", "F"],
    ["Jeff Teague", "G"],
    ["Robert Covington", "F"],
    ["Jake Layman", "G"],
    ["Shabazz Napier", "G"],
    ["Jarrett Culver", "G"],
  ],
  "2019-20|New Orleans Pelicans": [
    ["Jrue Holiday", "G"],
    ["Brandon Ingram", "F"],
    ["Josh Hart", "F"],
    ["JJ Redick", "G"],
    ["Lonzo Ball", "G"],
    ["Derrick Favors", "C"],
    ["Nicolo Melli", "F"],
    ["Kenrich Williams", "F"],
  ],
  "2019-20|New York Knicks": [
    ["Marcus Morris Sr.", "F"],
    ["RJ Barrett", "G"],
    ["Julius Randle", "F"],
    ["Bobby Portis", "C"],
    ["Elfrid Payton", "G"],
    ["Kevin Knox II", "F"],
    ["Taj Gibson", "C"],
    ["Wayne Ellington", "G"],
  ],
  "2019-20|Oklahoma City Thunder": [
    ["Shai Gilgeous-Alexander", "G"],
    ["Dennis Schroder", "G"],
    ["Chris Paul", "G"],
    ["Danilo Gallinari", "F"],
    ["Steven Adams", "C"],
    ["Terrance Ferguson", "F"],
    ["Hamidou Diallo", "F"],
    ["Darius Bazley", "F"],
  ],
  "2019-20|Orlando Magic": [
    ["Nikola Vucevic", "C"],
    ["Al-Farouq Aminu", "F"],
    ["Aaron Gordon", "F"],
    ["Evan Fournier", "G"],
    ["D.J. Augustin", "G"],
    ["Jonathan Isaac", "F"],
    ["Markelle Fultz", "G"],
    ["Terrence Ross", "C"],
  ],
  "2019-20|Philadelphia 76ers": [
    ["Tobias Harris", "F"],
    ["Ben Simmons", "G"],
    ["Josh Richardson", "G"],
    ["Al Horford", "F"],
    ["Joel Embiid", "C"],
    ["Matisse Thybulle", "F"],
    ["Furkan Korkmaz", "G"],
    ["James Ennis III", "F"],
  ],
  "2019-20|Phoenix Suns": [
    ["Deandre Ayton", "C"],
    ["Devin Booker", "G"],
    ["Kelly Oubre Jr.", "F"],
    ["Ricky Rubio", "G"],
    ["Mikal Bridges", "F"],
    ["Dario Saric", "F"],
    ["Frank Kaminsky", "C"],
    ["Jevon Carter", "G"],
  ],
  "2019-20|Portland Trail Blazers": [
    ["Damian Lillard", "G"],
    ["CJ McCollum", "G"],
    ["Rodney Hood", "F"],
    ["Zach Collins", "F"],
    ["Hassan Whiteside", "C"],
    ["Kent Bazemore", "F"],
    ["Mario Hezonja", "F"],
    ["Anthony Tolliver", "C"],
  ],
  "2019-20|Sacramento Kings": [
    ["Buddy Hield", "G"],
    ["Harrison Barnes", "F"],
    ["Marvin Bagley III", "C"],
    ["De'Aaron Fox", "G"],
    ["Bogdan Bogdanovic", "G"],
    ["Trevor Ariza", "F"],
    ["Cory Joseph", "G"],
    ["Nemanja Bjelica", "F"],
  ],
  "2019-20|San Antonio Spurs": [
    ["LaMarcus Aldridge", "F"],
    ["Bryn Forbes", "G"],
    ["DeMar DeRozan", "F"],
    ["Trey Lyles", "C"],
    ["Dejounte Murray", "G"],
    ["Derrick White", "G"],
    ["Rudy Gay", "C"],
    ["Marco Belinelli", "C"],
  ],
  "2019-20|Toronto Raptors": [
    ["Kyle Lowry", "G"],
    ["Fred VanVleet", "G"],
    ["Pascal Siakam", "F"],
    ["O.G. Anunoby", "F"],
    ["Marc Gasol", "C"],
    ["Norman Powell", "G"],
    ["Serge Ibaka", "C"],
    ["Terence Davis", "G"],
  ],
  "2019-20|Utah Jazz": [
    ["Rudy Gobert", "C"],
    ["Donovan Mitchell", "G"],
    ["Joe Ingles", "G"],
    ["Royce O'Neale", "F"],
    ["Mike Conley", "G"],
    ["Bojan Bogdanovic", "F"],
    ["Emmanuel Mudiay", "G"],
    ["Jeff Green", "F"],
  ],
  "2019-20|Washington Wizards": [
    ["Bradley Beal", "G"],
    ["Thomas Bryant", "C"],
    ["Davis Bertans", "F"],
    ["Rui Hachimura", "F"],
    ["Ish Smith", "G"],
    ["Jordan McRae", "F"],
    ["Isaac Bonga", "F"],
    ["Chris Chiozza", "G"],
  ],
  "2020-21|Atlanta Hawks": [
    ["Solomon Hill", "F"],
    ["Kevin Huerter", "G"],
    ["Trae Young", "G"],
    ["De'Andre Hunter", "F"],
    ["Bogdan Bogdanovic", "G"],
    ["Danilo Gallinari", "C"],
    ["Cam Reddish", "F"],
    ["Bruno Fernando", "C"],
  ],
  "2020-21|Boston Celtics": [
    ["Marcus Smart", "G"],
    ["Jaylen Brown", "G"],
    ["Jayson Tatum", "F"],
    ["Jeff Teague", "G"],
    ["Daniel Theis", "C"],
    ["Tristan Thompson", "C"],
    ["Semi Ojeleye", "F"],
    ["Grant Williams", "F"],
  ],
  "2020-21|Brooklyn Nets": [
    ["Kyrie Irving", "G"],
    ["Kevin Durant", "F"],
    ["Caris LeVert", "G"],
    ["Joe Harris", "F"],
    ["Spencer Dinwiddie", "G"],
    ["Landry Shamet", "G"],
    ["Jarrett Allen", "C"],
    ["Jeff Green", "F"],
  ],
  "2020-21|Charlotte Hornets": [
    ["Terry Rozier", "G"],
    ["Devonte' Graham", "G"],
    ["Gordon Hayward", "F"],
    ["Bismack Biyombo", "C"],
    ["Miles Bridges", "F"],
    ["P.J. Washington", "F"],
    ["Cody Martin", "F"],
    ["Cody Zeller", "C"],
  ],
  "2020-21|Chicago Bulls": [
    ["Patrick Williams", "F"],
    ["Coby White", "G"],
    ["Lauri Markkanen", "F"],
    ["Wendell Carter Jr.", "C"],
    ["Zach LaVine", "G"],
    ["Otto Porter Jr.", "F"],
    ["Ryan Arcidiacono", "G"],
    ["Chandler Hutchison", "C"],
  ],
  "2020-21|Cleveland Cavaliers": [
    ["Collin Sexton", "G"],
    ["Larry Nance Jr.", "F"],
    ["Isaac Okoro", "F"],
    ["Darius Garland", "G"],
    ["Andre Drummond", "C"],
    ["JaVale McGee", "C"],
    ["Cedi Osman", "F"],
    ["Dean Wade", "F"],
  ],
  "2020-21|Dallas Mavericks": [
    ["Josh Richardson", "G"],
    ["Luka Doncic", "G"],
    ["Dorian Finney-Smith", "F"],
    ["Maxi Kleber", "F"],
    ["Tim Hardaway Jr.", "F"],
    ["Trey Burke", "G"],
    ["Jalen Brunson", "G"],
    ["Dwight Powell", "C"],
  ],
  "2020-21|Denver Nuggets": [
    ["Nikola Jokic", "C"],
    ["Gary Harris", "G"],
    ["Paul Millsap", "F"],
    ["Jamal Murray", "G"],
    ["Will Barton", "G"],
    ["Michael Porter Jr.", "F"],
    ["Monte Morris", "G"],
    ["PJ Dozier", "G"],
  ],
  "2020-21|Detroit Pistons": [
    ["Blake Griffin", "F"],
    ["Mason Plumlee", "C"],
    ["Jerami Grant", "F"],
    ["Josh Jackson", "G"],
    ["Derrick Rose", "G"],
    ["Killian Hayes", "G"],
    ["Delon Wright", "G"],
    ["Svi Mykhailiuk", "G"],
  ],
  "2020-21|Golden State Warriors": [
    ["Andrew Wiggins", "F"],
    ["Stephen Curry", "G"],
    ["Kelly Oubre Jr.", "G"],
    ["James Wiseman", "C"],
    ["Brad Wanamaker", "G"],
    ["Eric Paschall", "F"],
    ["Jordan Poole", "G"],
    ["Juan Toscano-Anderson", "F"],
  ],
  "2020-21|Houston Rockets": [
    ["Christian Wood", "C"],
    ["James Harden", "G"],
    ["P.J. Tucker", "F"],
    ["Danuel House Jr.", "F"],
    ["Jae'Sean Tate", "F"],
    ["David Nwaba", "F"],
    ["Sterling Brown", "F"],
    ["Brodric Thomas", "G"],
  ],
  "2020-21|Indiana Pacers": [
    ["Domantas Sabonis", "F"],
    ["Malcolm Brogdon", "G"],
    ["Myles Turner", "C"],
    ["Doug McDermott", "F"],
    ["Victor Oladipo", "G"],
    ["T.J. Warren", "F"],
    ["Justin Holiday", "F"],
    ["T.J. McConnell", "G"],
  ],
  "2020-21|LA Clippers": [
    ["Paul George", "G"],
    ["Kawhi Leonard", "F"],
    ["Nicolas Batum", "F"],
    ["Ivica Zubac", "C"],
    ["Lou Williams", "G"],
    ["Patrick Beverley", "G"],
    ["Luke Kennard", "G"],
    ["Serge Ibaka", "C"],
  ],
  "2020-21|Los Angeles Lakers": [
    ["Montrezl Harrell", "C"],
    ["Anthony Davis", "F"],
    ["LeBron James", "F"],
    ["Dennis Schroder", "G"],
    ["Kyle Kuzma", "F"],
    ["Kentavious Caldwell-Pope", "G"],
    ["Markieff Morris", "F"],
    ["Alex Caruso", "G"],
  ],
  "2020-21|Memphis Grizzlies": [
    ["Ja Morant", "G"],
    ["Dillon Brooks", "F"],
    ["Jonas Valanciunas", "C"],
    ["Kyle Anderson", "F"],
    ["Grayson Allen", "G"],
    ["Brandon Clarke", "F"],
    ["De'Anthony Melton", "G"],
    ["Tyus Jones", "G"],
  ],
  "2020-21|Miami Heat": [
    ["Jimmy Butler", "F"],
    ["Bam Adebayo", "C"],
    ["Tyler Herro", "G"],
    ["Duncan Robinson", "G"],
    ["Goran Dragic", "G"],
    ["Maurice Harkless", "F"],
    ["Kelly Olynyk", "F"],
    ["Andre Iguodala", "F"],
  ],
  "2020-21|Milwaukee Bucks": [
    ["Jrue Holiday", "G"],
    ["Khris Middleton", "F"],
    ["Giannis Antetokounmpo", "F"],
    ["Brook Lopez", "C"],
    ["Donte DiVincenzo", "G"],
    ["Pat Connaughton", "F"],
    ["Bobby Portis", "F"],
    ["Bryn Forbes", "G"],
  ],
  "2020-21|Minnesota Timberwolves": [
    ["D'Angelo Russell", "G"],
    ["Josh Okogie", "F"],
    ["Karl-Anthony Towns", "C"],
    ["Malik Beasley", "G"],
    ["Ricky Rubio", "G"],
    ["Anthony Edwards", "G"],
    ["Jarrett Culver", "F"],
    ["Naz Reid", "C"],
  ],
  "2020-21|New Orleans Pelicans": [
    ["Brandon Ingram", "F"],
    ["Eric Bledsoe", "G"],
    ["Steven Adams", "C"],
    ["Zion Williamson", "F"],
    ["JJ Redick", "C"],
    ["Lonzo Ball", "G"],
    ["Josh Hart", "F"],
    ["Nicolo Melli", "F"],
  ],
  "2020-21|New York Knicks": [
    ["Julius Randle", "F"],
    ["RJ Barrett", "G"],
    ["Alec Burks", "F"],
    ["Reggie Bullock", "F"],
    ["Obi Toppin", "F"],
    ["Elfrid Payton", "G"],
    ["Mitchell Robinson", "C"],
    ["Kevin Knox II", "C"],
  ],
  "2020-21|Oklahoma City Thunder": [
    ["Luguentz Dort", "F"],
    ["Shai Gilgeous-Alexander", "G"],
    ["Darius Bazley", "F"],
    ["Al Horford", "C"],
    ["George Hill", "G"],
    ["Theo Maledon", "G"],
    ["Hamidou Diallo", "G"],
    ["Mike Muscala", "F"],
  ],
  "2020-21|Orlando Magic": [
    ["Nikola Vucevic", "C"],
    ["Evan Fournier", "G"],
    ["Markelle Fultz", "G"],
    ["Terrence Ross", "F"],
    ["Aaron Gordon", "F"],
    ["Chuma Okeke", "F"],
    ["Cole Anthony", "G"],
    ["Dwayne Bacon", "G"],
  ],
  "2020-21|Philadelphia 76ers": [
    ["Joel Embiid", "C"],
    ["Ben Simmons", "G"],
    ["Seth Curry", "G"],
    ["Tobias Harris", "F"],
    ["Shake Milton", "G"],
    ["Furkan Korkmaz", "F"],
    ["Danny Green", "F"],
    ["Mike Scott", "C"],
  ],
  "2020-21|Phoenix Suns": [
    ["Mikal Bridges", "F"],
    ["Devin Booker", "G"],
    ["Chris Paul", "G"],
    ["Jae Crowder", "F"],
    ["Cameron Johnson", "F"],
    ["Deandre Ayton", "C"],
    ["Cameron Payne", "G"],
    ["Jalen Smith", "F"],
  ],
  "2020-21|Portland Trail Blazers": [
    ["CJ McCollum", "G"],
    ["Damian Lillard", "G"],
    ["Gary Trent Jr.", "G"],
    ["Enes Freedom", "C"],
    ["Derrick Jones Jr.", "F"],
    ["Carmelo Anthony", "F"],
    ["Jusuf Nurkic", "C"],
    ["Robert Covington", "F"],
  ],
  "2020-21|Sacramento Kings": [
    ["Harrison Barnes", "F"],
    ["Buddy Hield", "G"],
    ["De'Aaron Fox", "G"],
    ["Tyrese Haliburton", "G"],
    ["Cory Joseph", "F"],
    ["Marvin Bagley III", "F"],
    ["Richaun Holmes", "C"],
    ["Hassan Whiteside", "C"],
  ],
  "2020-21|San Antonio Spurs": [
    ["DeMar DeRozan", "F"],
    ["Lonnie Walker IV", "G"],
    ["Keldon Johnson", "F"],
    ["Dejounte Murray", "G"],
    ["LaMarcus Aldridge", "C"],
    ["Rudy Gay", "F"],
    ["Devin Vassell", "G"],
    ["Patty Mills", "G"],
  ],
  "2020-21|Toronto Raptors": [
    ["Pascal Siakam", "F"],
    ["Kyle Lowry", "G"],
    ["O.G. Anunoby", "F"],
    ["Fred VanVleet", "G"],
    ["Aron Baynes", "C"],
    ["Norman Powell", "F"],
    ["Matt Thomas", "F"],
    ["Chris Boucher", "C"],
  ],
  "2020-21|Utah Jazz": [
    ["Bojan Bogdanovic", "F"],
    ["Donovan Mitchell", "G"],
    ["Mike Conley", "G"],
    ["Rudy Gobert", "C"],
    ["Royce O'Neale", "F"],
    ["Joe Ingles", "G"],
    ["Jordan Clarkson", "G"],
    ["Derrick Favors", "C"],
  ],
  "2020-21|Washington Wizards": [
    ["Russell Westbrook", "G"],
    ["Bradley Beal", "G"],
    ["Deni Avdija", "F"],
    ["Thomas Bryant", "C"],
    ["Ish Smith", "G"],
    ["Troy Brown Jr.", "F"],
    ["Davis Bertans", "F"],
    ["Isaac Bonga", "F"],
  ],
  "2021-22|Atlanta Hawks": [
    ["Trae Young", "G"],
    ["John Collins", "F"],
    ["De'Andre Hunter", "F"],
    ["Bogdan Bogdanovic", "G"],
    ["Kevin Huerter", "G"],
    ["Cam Reddish", "F"],
    ["Clint Capela", "C"],
    ["Delon Wright", "G"],
  ],
  "2021-22|Boston Celtics": [
    ["Jaylen Brown", "G"],
    ["Marcus Smart", "G"],
    ["Robert Williams III", "C"],
    ["Jayson Tatum", "F"],
    ["Dennis Schroder", "G"],
    ["Grant Williams", "F"],
    ["Romeo Langford", "F"],
    ["Aaron Nesmith", "F"],
  ],
  "2021-22|Brooklyn Nets": [
    ["Joe Harris", "G"],
    ["James Harden", "G"],
    ["Kevin Durant", "F"],
    ["Patty Mills", "G"],
    ["Nic Claxton", "C"],
    ["Blake Griffin", "C"],
    ["James Johnson", "F"],
    ["Jevon Carter", "G"],
  ],
  "2021-22|Charlotte Hornets": [
    ["Gordon Hayward", "F"],
    ["Kelly Oubre Jr.", "G"],
    ["Miles Bridges", "F"],
    ["Mason Plumlee", "C"],
    ["LaMelo Ball", "G"],
    ["Cody Martin", "G"],
    ["Ish Smith", "G"],
    ["P.J. Washington", "F"],
  ],
  "2021-22|Chicago Bulls": [
    ["DeMar DeRozan", "F"],
    ["Nikola Vucevic", "C"],
    ["Zach LaVine", "G"],
    ["Lonzo Ball", "G"],
    ["Patrick Williams", "F"],
    ["Alex Caruso", "G"],
    ["Javonte Green", "F"],
    ["Alize Johnson", "C"],
  ],
  "2021-22|Cleveland Cavaliers": [
    ["Evan Mobley", "F"],
    ["Darius Garland", "G"],
    ["Lauri Markkanen", "F"],
    ["Collin Sexton", "G"],
    ["Jarrett Allen", "C"],
    ["Ricky Rubio", "G"],
    ["Isaac Okoro", "G"],
    ["Kevin Love", "F"],
  ],
  "2021-22|Dallas Mavericks": [
    ["Luka Doncic", "G"],
    ["Kristaps Porzingis", "F"],
    ["Dorian Finney-Smith", "F"],
    ["Tim Hardaway Jr.", "G"],
    ["Jalen Brunson", "G"],
    ["Dwight Powell", "C"],
    ["Maxi Kleber", "F"],
    ["Reggie Bullock", "F"],
  ],
  "2021-22|Denver Nuggets": [
    ["Nikola Jokic", "C"],
    ["Michael Porter Jr.", "F"],
    ["Will Barton", "G"],
    ["Aaron Gordon", "F"],
    ["Monte Morris", "G"],
    ["PJ Dozier", "F"],
    ["Facundo Campazzo", "G"],
    ["Jeff Green", "F"],
  ],
  "2021-22|Detroit Pistons": [
    ["Saddiq Bey", "F"],
    ["Jerami Grant", "F"],
    ["Frank Jackson", "G"],
    ["Cory Joseph", "G"],
    ["Isaiah Stewart", "C"],
    ["Kelly Olynyk", "F"],
    ["Killian Hayes", "G"],
    ["Josh Jackson", "F"],
  ],
  "2021-22|Golden State Warriors": [
    ["Stephen Curry", "G"],
    ["Draymond Green", "F"],
    ["Damion Lee", "G"],
    ["Nemanja Bjelica", "F"],
    ["Andrew Wiggins", "F"],
    ["Jordan Poole", "G"],
    ["Andre Iguodala", "G"],
    ["Kevon Looney", "C"],
  ],
  "2021-22|Houston Rockets": [
    ["Jalen Green", "G"],
    ["Christian Wood", "C"],
    ["Kevin Porter Jr.", "G"],
    ["Eric Gordon", "F"],
    ["Jae'Sean Tate", "F"],
    ["Daniel Theis", "C"],
    ["Alperen Sengun", "C"],
    ["David Nwaba", "F"],
  ],
  "2021-22|Indiana Pacers": [
    ["Malcolm Brogdon", "G"],
    ["Domantas Sabonis", "F"],
    ["Chris Duarte", "G"],
    ["Torrey Craig", "F"],
    ["Myles Turner", "C"],
    ["Justin Holiday", "F"],
    ["Jeremy Lamb", "F"],
    ["T.J. McConnell", "G"],
  ],
  "2021-22|LA Clippers": [
    ["Terance Mann", "F"],
    ["Reggie Jackson", "G"],
    ["Paul George", "F"],
    ["Eric Bledsoe", "G"],
    ["Marcus Morris Sr.", "F"],
    ["Luke Kennard", "G"],
    ["Ivica Zubac", "C"],
    ["Amir Coffey", "G"],
  ],
  "2021-22|Los Angeles Lakers": [
    ["Anthony Davis", "C"],
    ["LeBron James", "F"],
    ["Russell Westbrook", "G"],
    ["Kent Bazemore", "F"],
    ["Carmelo Anthony", "F"],
    ["Rajon Rondo", "G"],
    ["Malik Monk", "G"],
    ["DeAndre Jordan", "C"],
  ],
  "2021-22|Memphis Grizzlies": [
    ["Ja Morant", "G"],
    ["Steven Adams", "C"],
    ["Jaren Jackson Jr.", "F"],
    ["De'Anthony Melton", "G"],
    ["Desmond Bane", "G"],
    ["Kyle Anderson", "F"],
    ["John Konchar", "G"],
    ["Ziaire Williams", "F"],
  ],
  "2021-22|Miami Heat": [
    ["Jimmy Butler", "F"],
    ["Kyle Lowry", "G"],
    ["Tyler Herro", "G"],
    ["Duncan Robinson", "G"],
    ["Bam Adebayo", "C"],
    ["P.J. Tucker", "F"],
    ["Max Strus", "G"],
    ["Markieff Morris", "F"],
  ],
  "2021-22|Milwaukee Bucks": [
    ["Giannis Antetokounmpo", "F"],
    ["Khris Middleton", "F"],
    ["Pat Connaughton", "F"],
    ["Brook Lopez", "C"],
    ["Grayson Allen", "G"],
    ["Jordan Nwora", "G"],
    ["George Hill", "G"],
    ["Jrue Holiday", "G"],
  ],
  "2021-22|Minnesota Timberwolves": [
    ["Anthony Edwards", "F"],
    ["Karl-Anthony Towns", "C"],
    ["Jaden McDaniels", "F"],
    ["D'Angelo Russell", "G"],
    ["Josh Okogie", "F"],
    ["Malik Beasley", "G"],
    ["Jordan McLaughlin", "G"],
    ["Naz Reid", "C"],
  ],
  "2021-22|New Orleans Pelicans": [
    ["Brandon Ingram", "F"],
    ["Nickeil Alexander-Walker", "G"],
    ["Jonas Valanciunas", "C"],
    ["Devonte' Graham", "G"],
    ["Naji Marshall", "F"],
    ["Jaxson Hayes", "F"],
    ["Trey Murphy III", "F"],
    ["Kira Lewis Jr.", "G"],
  ],
  "2021-22|New York Knicks": [
    ["RJ Barrett", "F"],
    ["Julius Randle", "F"],
    ["Evan Fournier", "G"],
    ["Kemba Walker", "G"],
    ["Mitchell Robinson", "C"],
    ["Obi Toppin", "F"],
    ["Derrick Rose", "G"],
    ["Alec Burks", "G"],
  ],
  "2021-22|Oklahoma City Thunder": [
    ["Shai Gilgeous-Alexander", "G"],
    ["Darius Bazley", "F"],
    ["Luguentz Dort", "F"],
    ["Josh Giddey", "G"],
    ["Theo Maledon", "G"],
    ["Derrick Favors", "C"],
    ["Kenrich Williams", "F"],
    ["Aleksej Pokusevski", "F"],
  ],
  "2021-22|Orlando Magic": [
    ["Franz Wagner", "F"],
    ["Jalen Suggs", "G"],
    ["Cole Anthony", "G"],
    ["Terrence Ross", "F"],
    ["Mo Bamba", "C"],
    ["R.J. Hampton", "G"],
    ["Ignas Brazdeikis", "F"],
    ["Wendell Carter Jr.", "F"],
  ],
  "2021-22|Philadelphia 76ers": [
    ["Tyrese Maxey", "G"],
    ["Tobias Harris", "F"],
    ["Seth Curry", "G"],
    ["Matisse Thybulle", "F"],
    ["Joel Embiid", "C"],
    ["Furkan Korkmaz", "G"],
    ["Andre Drummond", "C"],
    ["Danny Green", "F"],
  ],
  "2021-22|Phoenix Suns": [
    ["Chris Paul", "G"],
    ["Mikal Bridges", "F"],
    ["Deandre Ayton", "C"],
    ["Devin Booker", "G"],
    ["Jae Crowder", "F"],
    ["Cameron Johnson", "F"],
    ["Landry Shamet", "G"],
    ["JaVale McGee", "C"],
  ],
  "2021-22|Portland Trail Blazers": [
    ["Damian Lillard", "G"],
    ["CJ McCollum", "G"],
    ["Norman Powell", "F"],
    ["Robert Covington", "F"],
    ["Jusuf Nurkic", "C"],
    ["Cody Zeller", "C"],
    ["Anfernee Simons", "G"],
    ["Larry Nance Jr.", "F"],
  ],
  "2021-22|Sacramento Kings": [
    ["Harrison Barnes", "F"],
    ["De'Aaron Fox", "G"],
    ["Buddy Hield", "G"],
    ["Richaun Holmes", "C"],
    ["Tyrese Haliburton", "G"],
    ["Davion Mitchell", "G"],
    ["Maurice Harkless", "F"],
    ["Tristan Thompson", "C"],
  ],
  "2021-22|San Antonio Spurs": [
    ["Dejounte Murray", "G"],
    ["Derrick White", "G"],
    ["Jakob Poeltl", "C"],
    ["Keldon Johnson", "F"],
    ["Lonnie Walker IV", "G"],
    ["Devin Vassell", "F"],
    ["Doug McDermott", "F"],
    ["Drew Eubanks", "C"],
  ],
  "2021-22|Toronto Raptors": [
    ["Fred VanVleet", "G"],
    ["O.G. Anunoby", "F"],
    ["Scottie Barnes", "F"],
    ["Gary Trent Jr.", "G"],
    ["Khem Birch", "C"],
    ["Goran Dragic", "G"],
    ["Precious Achiuwa", "C"],
    ["Chris Boucher", "C"],
  ],
  "2021-22|Utah Jazz": [
    ["Rudy Gobert", "C"],
    ["Donovan Mitchell", "G"],
    ["Bojan Bogdanovic", "F"],
    ["Royce O'Neale", "F"],
    ["Jordan Clarkson", "G"],
    ["Joe Ingles", "G"],
    ["Mike Conley", "G"],
    ["Hassan Whiteside", "C"],
  ],
  "2021-22|Washington Wizards": [
    ["Kyle Kuzma", "F"],
    ["Bradley Beal", "G"],
    ["Kentavious Caldwell-Pope", "F"],
    ["Spencer Dinwiddie", "G"],
    ["Montrezl Harrell", "C"],
    ["Raul Neto", "G"],
    ["Daniel Gafford", "C"],
    ["Deni Avdija", "F"],
  ],
  "2022-23|Atlanta Hawks": [
    ["Dejounte Murray", "G"],
    ["Trae Young", "G"],
    ["John Collins", "F"],
    ["De'Andre Hunter", "F"],
    ["Clint Capela", "C"],
    ["Onyeka Okongwu", "C"],
    ["Justin Holiday", "F"],
    ["Aaron Holiday", "G"],
  ],
  "2022-23|Boston Celtics": [
    ["Jayson Tatum", "F"],
    ["Jaylen Brown", "F"],
    ["Marcus Smart", "G"],
    ["Derrick White", "G"],
    ["Grant Williams", "F"],
    ["Malcolm Brogdon", "G"],
    ["Al Horford", "C"],
    ["Noah Vonleh", "C"],
  ],
  "2022-23|Brooklyn Nets": [
    ["Kyrie Irving", "G"],
    ["Royce O'Neale", "F"],
    ["Kevin Durant", "F"],
    ["Nic Claxton", "C"],
    ["Ben Simmons", "G"],
    ["Patty Mills", "G"],
    ["Day'Ron Sharpe", "C"],
    ["Edmond Sumner", "G"],
  ],
  "2022-23|Charlotte Hornets": [
    ["P.J. Washington", "F"],
    ["Terry Rozier", "G"],
    ["Gordon Hayward", "F"],
    ["Jalen McDaniels", "F"],
    ["Kelly Oubre Jr.", "G"],
    ["Mason Plumlee", "C"],
    ["Nick Richards", "C"],
    ["Dennis Smith Jr.", "G"],
  ],
  "2022-23|Chicago Bulls": [
    ["Ayo Dosunmu", "G"],
    ["DeMar DeRozan", "F"],
    ["Nikola Vucevic", "C"],
    ["Alex Caruso", "F"],
    ["Patrick Williams", "F"],
    ["Coby White", "G"],
    ["Goran Dragic", "G"],
    ["Javonte Green", "F"],
  ],
  "2022-23|Cleveland Cavaliers": [
    ["Evan Mobley", "F"],
    ["Caris LeVert", "G"],
    ["Donovan Mitchell", "G"],
    ["Jarrett Allen", "C"],
    ["Cedi Osman", "G"],
    ["Dean Wade", "F"],
    ["Kevin Love", "F"],
    ["Darius Garland", "G"],
  ],
  "2022-23|Dallas Mavericks": [
    ["Dorian Finney-Smith", "F"],
    ["Luka Doncic", "G"],
    ["Reggie Bullock", "F"],
    ["Spencer Dinwiddie", "G"],
    ["Maxi Kleber", "F"],
    ["Tim Hardaway Jr.", "F"],
    ["Christian Wood", "C"],
    ["Josh Green", "F"],
  ],
  "2022-23|Denver Nuggets": [
    ["Michael Porter Jr.", "F"],
    ["Kentavious Caldwell-Pope", "G"],
    ["Nikola Jokic", "C"],
    ["Aaron Gordon", "F"],
    ["Jamal Murray", "G"],
    ["Bruce Brown", "G"],
    ["Bones Hyland", "G"],
    ["Jeff Green", "F"],
  ],
  "2022-23|Detroit Pistons": [
    ["Cade Cunningham", "G"],
    ["Bojan Bogdanovic", "F"],
    ["Jaden Ivey", "G"],
    ["Saddiq Bey", "F"],
    ["Isaiah Stewart", "F"],
    ["Jalen Duren", "C"],
    ["Killian Hayes", "G"],
    ["Cory Joseph", "G"],
  ],
  "2022-23|Golden State Warriors": [
    ["Stephen Curry", "G"],
    ["Andrew Wiggins", "F"],
    ["Jordan Poole", "G"],
    ["Draymond Green", "F"],
    ["JaMychal Green", "F"],
    ["Donte DiVincenzo", "F"],
    ["Kevon Looney", "C"],
    ["Klay Thompson", "G"],
  ],
  "2022-23|Houston Rockets": [
    ["Kevin Porter Jr.", "G"],
    ["Jabari Smith Jr.", "F"],
    ["Jalen Green", "G"],
    ["Eric Gordon", "F"],
    ["Bruno Fernando", "C"],
    ["Kenyon Martin Jr.", "F"],
    ["Alperen Sengun", "C"],
    ["Tari Eason", "F"],
  ],
  "2022-23|Indiana Pacers": [
    ["Tyrese Haliburton", "G"],
    ["Buddy Hield", "F"],
    ["Bennedict Mathurin", "F"],
    ["Terry Taylor", "F"],
    ["Aaron Nesmith", "F"],
    ["Jalen Smith", "F"],
    ["Chris Duarte", "G"],
    ["T.J. McConnell", "G"],
  ],
  "2022-23|LA Clippers": [
    ["Paul George", "G"],
    ["Ivica Zubac", "C"],
    ["John Wall", "G"],
    ["Luke Kennard", "G"],
    ["Reggie Jackson", "G"],
    ["Marcus Morris Sr.", "F"],
    ["Norman Powell", "G"],
    ["Kawhi Leonard", "F"],
  ],
  "2022-23|Los Angeles Lakers": [
    ["Anthony Davis", "C"],
    ["LeBron James", "F"],
    ["Russell Westbrook", "G"],
    ["Lonnie Walker IV", "F"],
    ["Patrick Beverley", "G"],
    ["Kendrick Nunn", "G"],
    ["Matt Ryan", "F"],
    ["Austin Reaves", "G"],
  ],
  "2022-23|Memphis Grizzlies": [
    ["Santi Aldama", "F"],
    ["Ja Morant", "G"],
    ["Desmond Bane", "G"],
    ["John Konchar", "G"],
    ["Steven Adams", "C"],
    ["Tyus Jones", "G"],
    ["Brandon Clarke", "C"],
    ["Xavier Tillman", "C"],
  ],
  "2022-23|Miami Heat": [
    ["Jimmy Butler", "F"],
    ["Kyle Lowry", "G"],
    ["Tyler Herro", "G"],
    ["Bam Adebayo", "C"],
    ["Max Strus", "G"],
    ["Caleb Martin", "F"],
    ["Gabe Vincent", "G"],
    ["Dewayne Dedmon", "C"],
  ],
  "2022-23|Milwaukee Bucks": [
    ["Giannis Antetokounmpo", "F"],
    ["Jrue Holiday", "G"],
    ["Grayson Allen", "G"],
    ["Brook Lopez", "C"],
    ["Bobby Portis", "F"],
    ["Jevon Carter", "G"],
    ["George Hill", "G"],
    ["Wesley Matthews", "F"],
  ],
  "2022-23|Minnesota Timberwolves": [
    ["Jaden McDaniels", "F"],
    ["Karl-Anthony Towns", "F"],
    ["D'Angelo Russell", "G"],
    ["Rudy Gobert", "C"],
    ["Anthony Edwards", "G"],
    ["Kyle Anderson", "F"],
    ["Jaylen Nowell", "G"],
    ["Taurean Prince", "G"],
  ],
  "2022-23|New Orleans Pelicans": [
    ["CJ McCollum", "G"],
    ["Brandon Ingram", "F"],
    ["Zion Williamson", "F"],
    ["Herbert Jones", "G"],
    ["Jonas Valanciunas", "C"],
    ["Trey Murphy III", "F"],
    ["Larry Nance Jr.", "C"],
    ["Jose Alvarado", "G"],
  ],
  "2022-23|New York Knicks": [
    ["Isaiah Hartenstein", "C"],
    ["RJ Barrett", "F"],
    ["Jalen Brunson", "G"],
    ["Julius Randle", "F"],
    ["Evan Fournier", "G"],
    ["Cam Reddish", "G"],
    ["Immanuel Quickley", "G"],
    ["Obi Toppin", "F"],
  ],
  "2022-23|Oklahoma City Thunder": [
    ["Shai Gilgeous-Alexander", "G"],
    ["Josh Giddey", "G"],
    ["Luguentz Dort", "F"],
    ["Aleksej Pokusevski", "C"],
    ["Tre Mann", "G"],
    ["Kenrich Williams", "C"],
    ["Darius Bazley", "C"],
    ["Eugene Omoruyi", "F"],
  ],
  "2022-23|Orlando Magic": [
    ["Paolo Banchero", "F"],
    ["Franz Wagner", "F"],
    ["Wendell Carter Jr.", "C"],
    ["Terrence Ross", "G"],
    ["Jalen Suggs", "G"],
    ["Caleb Houstan", "G"],
    ["Chuma Okeke", "F"],
    ["Bol Bol", "F"],
  ],
  "2022-23|Philadelphia 76ers": [
    ["Tyrese Maxey", "G"],
    ["James Harden", "G"],
    ["Joel Embiid", "C"],
    ["Tobias Harris", "F"],
    ["P.J. Tucker", "F"],
    ["De'Anthony Melton", "G"],
    ["Danuel House Jr.", "F"],
    ["Georges Niang", "F"],
  ],
  "2022-23|Phoenix Suns": [
    ["Mikal Bridges", "F"],
    ["Devin Booker", "G"],
    ["Deandre Ayton", "C"],
    ["Chris Paul", "G"],
    ["Cameron Johnson", "F"],
    ["Damion Lee", "G"],
    ["Cameron Payne", "G"],
    ["Jock Landale", "F"],
  ],
  "2022-23|Portland Trail Blazers": [
    ["Josh Hart", "F"],
    ["Damian Lillard", "G"],
    ["Anfernee Simons", "G"],
    ["Jerami Grant", "F"],
    ["Justise Winslow", "G"],
    ["Jusuf Nurkic", "C"],
    ["Shaedon Sharpe", "G"],
    ["Drew Eubanks", "C"],
  ],
  "2022-23|Sacramento Kings": [
    ["De'Aaron Fox", "G"],
    ["Domantas Sabonis", "C"],
    ["Harrison Barnes", "F"],
    ["Kevin Huerter", "G"],
    ["Davion Mitchell", "G"],
    ["Terence Davis", "G"],
    ["KZ Okpala", "F"],
    ["Malik Monk", "G"],
  ],
  "2022-23|San Antonio Spurs": [
    ["Keldon Johnson", "F"],
    ["Devin Vassell", "G"],
    ["Jeremy Sochan", "F"],
    ["Jakob Poeltl", "C"],
    ["Joshua Primo", "G"],
    ["Tre Jones", "G"],
    ["Josh Richardson", "G"],
    ["Doug McDermott", "C"],
  ],
  "2022-23|Toronto Raptors": [
    ["Fred VanVleet", "G"],
    ["O.G. Anunoby", "F"],
    ["Gary Trent Jr.", "G"],
    ["Pascal Siakam", "F"],
    ["Scottie Barnes", "G"],
    ["Precious Achiuwa", "C"],
    ["Christian Koloko", "C"],
    ["Thaddeus Young", "C"],
  ],
  "2022-23|Utah Jazz": [
    ["Lauri Markkanen", "F"],
    ["Mike Conley", "G"],
    ["Jordan Clarkson", "G"],
    ["Rudy Gay", "F"],
    ["Malik Beasley", "F"],
    ["Walker Kessler", "C"],
    ["Collin Sexton", "G"],
    ["Jarred Vanderbilt", "C"],
  ],
  "2022-23|Washington Wizards": [
    ["Bradley Beal", "G"],
    ["Kyle Kuzma", "F"],
    ["Kristaps Porzingis", "C"],
    ["Delon Wright", "G"],
    ["Will Barton", "G"],
    ["Rui Hachimura", "F"],
    ["Monte Morris", "G"],
    ["Daniel Gafford", "C"],
  ],
  "2023-24|Atlanta Hawks": [
    ["Trae Young", "G"],
    ["Dejounte Murray", "G"],
    ["De'Andre Hunter", "F"],
    ["Jalen Johnson", "F"],
    ["Saddiq Bey", "F"],
    ["Clint Capela", "C"],
    ["Bogdan Bogdanovic", "G"],
    ["Onyeka Okongwu", "C"],
  ],
  "2023-24|Boston Celtics": [
    ["Jayson Tatum", "F"],
    ["Jaylen Brown", "F"],
    ["Kristaps Porzingis", "C"],
    ["Jrue Holiday", "G"],
    ["Derrick White", "G"],
    ["Al Horford", "C"],
    ["Sam Hauser", "F"],
    ["Payton Pritchard", "G"],
  ],
  "2023-24|Brooklyn Nets": [
    ["Mikal Bridges", "F"],
    ["Nic Claxton", "C"],
    ["Dorian Finney-Smith", "F"],
    ["Cameron Johnson", "F"],
    ["Cam Thomas", "G"],
    ["Spencer Dinwiddie", "G"],
    ["Ben Simmons", "G"],
    ["Royce O'Neale", "F"],
  ],
  "2023-24|Charlotte Hornets": [
    ["Terry Rozier", "G"],
    ["Gordon Hayward", "F"],
    ["P.J. Washington", "F"],
    ["LaMelo Ball", "G"],
    ["Mark Williams", "C"],
    ["Brandon Miller", "G"],
    ["JT Thor", "F"],
    ["Nick Richards", "C"],
  ],
  "2023-24|Chicago Bulls": [
    ["DeMar DeRozan", "F"],
    ["Nikola Vucevic", "C"],
    ["Coby White", "G"],
    ["Patrick Williams", "F"],
    ["Zach LaVine", "G"],
    ["Torrey Craig", "F"],
    ["Alex Caruso", "F"],
    ["Andre Drummond", "C"],
  ],
  "2023-24|Cleveland Cavaliers": [
    ["Max Strus", "F"],
    ["Donovan Mitchell", "G"],
    ["Evan Mobley", "F"],
    ["Darius Garland", "G"],
    ["Isaac Okoro", "F"],
    ["Caris LeVert", "G"],
    ["Georges Niang", "F"],
    ["Damian Jones", "C"],
  ],
  "2023-24|Dallas Mavericks": [
    ["Kyrie Irving", "G"],
    ["Grant Williams", "F"],
    ["Luka Doncic", "G"],
    ["Dereck Lively II", "C"],
    ["Josh Green", "F"],
    ["Tim Hardaway Jr.", "G"],
    ["Maxi Kleber", "C"],
    ["Derrick Jones Jr.", "F"],
  ],
  "2023-24|Denver Nuggets": [
    ["Nikola Jokic", "C"],
    ["Kentavious Caldwell-Pope", "G"],
    ["Aaron Gordon", "F"],
    ["Jamal Murray", "G"],
    ["Michael Porter Jr.", "F"],
    ["Reggie Jackson", "G"],
    ["Christian Braun", "F"],
    ["Zeke Nnaji", "C"],
  ],
  "2023-24|Detroit Pistons": [
    ["Cade Cunningham", "G"],
    ["Isaiah Stewart", "F"],
    ["Jalen Duren", "C"],
    ["Killian Hayes", "G"],
    ["Ausar Thompson", "F"],
    ["Alec Burks", "G"],
    ["Jaden Ivey", "G"],
    ["Marvin Bagley III", "C"],
  ],
  "2023-24|Golden State Warriors": [
    ["Klay Thompson", "G"],
    ["Chris Paul", "G"],
    ["Stephen Curry", "G"],
    ["Kevon Looney", "C"],
    ["Andrew Wiggins", "F"],
    ["Gary Payton II", "F"],
    ["Jonathan Kuminga", "F"],
    ["Dario Saric", "F"],
  ],
  "2023-24|Houston Rockets": [
    ["Fred VanVleet", "G"],
    ["Jalen Green", "G"],
    ["Alperen Sengun", "C"],
    ["Jabari Smith Jr.", "F"],
    ["Dillon Brooks", "F"],
    ["Amen Thompson", "F"],
    ["Jae'Sean Tate", "F"],
    ["Jeff Green", "F"],
  ],
  "2023-24|Indiana Pacers": [
    ["Bruce Brown", "G"],
    ["Tyrese Haliburton", "G"],
    ["Bennedict Mathurin", "F"],
    ["Buddy Hield", "F"],
    ["Myles Turner", "C"],
    ["Aaron Nesmith", "F"],
    ["Andrew Nembhard", "G"],
    ["Obi Toppin", "F"],
  ],
  "2023-24|LA Clippers": [
    ["Paul George", "F"],
    ["Russell Westbrook", "G"],
    ["Kawhi Leonard", "F"],
    ["Ivica Zubac", "C"],
    ["Robert Covington", "F"],
    ["Norman Powell", "G"],
    ["Bones Hyland", "G"],
    ["Mason Plumlee", "C"],
  ],
  "2023-24|Los Angeles Lakers": [
    ["D'Angelo Russell", "G"],
    ["Anthony Davis", "C"],
    ["Austin Reaves", "G"],
    ["Taurean Prince", "G"],
    ["LeBron James", "F"],
    ["Gabe Vincent", "G"],
    ["Cam Reddish", "F"],
    ["Christian Wood", "C"],
  ],
  "2023-24|Memphis Grizzlies": [
    ["Desmond Bane", "G"],
    ["Jaren Jackson Jr.", "F"],
    ["Xavier Tillman", "C"],
    ["Marcus Smart", "G"],
    ["Ziaire Williams", "F"],
    ["David Roddy", "F"],
    ["Derrick Rose", "G"],
    ["Luke Kennard", "G"],
  ],
  "2023-24|Miami Heat": [
    ["Tyler Herro", "G"],
    ["Jimmy Butler", "F"],
    ["Bam Adebayo", "C"],
    ["Kyle Lowry", "G"],
    ["Kevin Love", "F"],
    ["Duncan Robinson", "G"],
    ["Caleb Martin", "F"],
    ["Thomas Bryant", "C"],
  ],
  "2023-24|Milwaukee Bucks": [
    ["Damian Lillard", "G"],
    ["Giannis Antetokounmpo", "F"],
    ["Malik Beasley", "G"],
    ["Brook Lopez", "C"],
    ["Jae Crowder", "F"],
    ["Pat Connaughton", "G"],
    ["Bobby Portis", "F"],
    ["MarJon Beauchamp", "G"],
  ],
  "2023-24|Minnesota Timberwolves": [
    ["Anthony Edwards", "G"],
    ["Karl-Anthony Towns", "F"],
    ["Rudy Gobert", "C"],
    ["Mike Conley", "G"],
    ["Kyle Anderson", "F"],
    ["Naz Reid", "F"],
    ["Nickeil Alexander-Walker", "F"],
    ["Shake Milton", "C"],
  ],
  "2023-24|New Orleans Pelicans": [
    ["Herbert Jones", "G"],
    ["CJ McCollum", "G"],
    ["Brandon Ingram", "F"],
    ["Zion Williamson", "F"],
    ["Jonas Valanciunas", "C"],
    ["Dyson Daniels", "G"],
    ["Larry Nance Jr.", "F"],
    ["Matt Ryan", "F"],
  ],
  "2023-24|New York Knicks": [
    ["RJ Barrett", "F"],
    ["Julius Randle", "F"],
    ["Jalen Brunson", "G"],
    ["Immanuel Quickley", "F"],
    ["Isaiah Hartenstein", "C"],
    ["Quentin Grimes", "G"],
    ["Josh Hart", "F"],
    ["Mitchell Robinson", "C"],
  ],
  "2023-24|Oklahoma City Thunder": [
    ["Shai Gilgeous-Alexander", "G"],
    ["Luguentz Dort", "F"],
    ["Jalen Williams", "F"],
    ["Josh Giddey", "G"],
    ["Chet Holmgren", "C"],
    ["Isaiah Joe", "G"],
    ["Cason Wallace", "F"],
    ["Ousmane Dieng", "F"],
  ],
  "2023-24|Orlando Magic": [
    ["Paolo Banchero", "F"],
    ["Franz Wagner", "F"],
    ["Wendell Carter Jr.", "C"],
    ["Markelle Fultz", "G"],
    ["Cole Anthony", "G"],
    ["Jalen Suggs", "G"],
    ["Joe Ingles", "G"],
    ["Gary Harris", "G"],
  ],
  "2023-24|Philadelphia 76ers": [
    ["Tyrese Maxey", "G"],
    ["Tobias Harris", "F"],
    ["Joel Embiid", "C"],
    ["Kelly Oubre Jr.", "F"],
    ["P.J. Tucker", "F"],
    ["De'Anthony Melton", "G"],
    ["Danny Green", "F"],
    ["Patrick Beverley", "G"],
  ],
  "2023-24|Phoenix Suns": [
    ["Devin Booker", "G"],
    ["Kevin Durant", "F"],
    ["Eric Gordon", "G"],
    ["Josh Okogie", "F"],
    ["Jusuf Nurkic", "C"],
    ["Grayson Allen", "F"],
    ["Drew Eubanks", "C"],
    ["Yuta Watanabe", "C"],
  ],
  "2023-24|Portland Trail Blazers": [
    ["Scoot Henderson", "G"],
    ["Jerami Grant", "F"],
    ["Shaedon Sharpe", "G"],
    ["Anfernee Simons", "G"],
    ["Robert Williams III", "C"],
    ["Deandre Ayton", "C"],
    ["Malcolm Brogdon", "G"],
    ["Matisse Thybulle", "F"],
  ],
  "2023-24|Sacramento Kings": [
    ["Harrison Barnes", "F"],
    ["De'Aaron Fox", "G"],
    ["Domantas Sabonis", "C"],
    ["Keegan Murray", "F"],
    ["Kevin Huerter", "G"],
    ["Malik Monk", "G"],
    ["Sasha Vezenkov", "F"],
    ["Chris Duarte", "G"],
  ],
  "2023-24|San Antonio Spurs": [
    ["Devin Vassell", "G"],
    ["Zach Collins", "C"],
    ["Keldon Johnson", "F"],
    ["Jeremy Sochan", "F"],
    ["Tre Jones", "G"],
    ["Victor Wembanyama", "C"],
    ["Cedi Osman", "F"],
    ["Malaki Branham", "G"],
  ],
  "2023-24|Toronto Raptors": [
    ["Scottie Barnes", "F"],
    ["Pascal Siakam", "F"],
    ["OG Anunoby", "F"],
    ["Dennis Schroder", "G"],
    ["Gary Trent Jr.", "G"],
    ["Precious Achiuwa", "F"],
    ["Jakob Poeltl", "C"],
    ["Jalen McDaniels", "F"],
  ],
  "2023-24|Utah Jazz": [
    ["Lauri Markkanen", "F"],
    ["John Collins", "C"],
    ["Jordan Clarkson", "G"],
    ["Walker Kessler", "C"],
    ["Talen Horton-Tucker", "G"],
    ["Collin Sexton", "G"],
    ["Ochai Agbaji", "F"],
    ["Keyonte George", "G"],
  ],
  "2023-24|Washington Wizards": [
    ["Tyus Jones", "G"],
    ["Jordan Poole", "G"],
    ["Delon Wright", "G"],
    ["Kyle Kuzma", "F"],
    ["Corey Kispert", "G"],
    ["Bilal Coulibaly", "F"],
    ["Daniel Gafford", "C"],
    ["Deni Avdija", "F"],
  ],
};
